/**
 * Background utilities: attachment, clip, origin, position, repeat, size, image, gradients
 */
export const backgroundsMappings: Record<string, string> = {
  // Background Colors - Grays
  'bg-inherit': 'inherited background color',
  'bg-current': 'current color background',
  'bg-transparent': 'transparent background',
  'bg-white': 'white background',
  'bg-black': 'black background',
  'bg-gray-50': 'lightest gray background',
  'bg-gray-100': 'very light gray background',
  'bg-gray-200': 'light gray background',
  'bg-gray-300': 'lightish gray background',
  'bg-gray-400': 'medium light gray background',
  'bg-gray-500': 'medium gray background',
  'bg-gray-600': 'medium dark gray background',
  'bg-gray-700': 'dark gray background',
  'bg-gray-800': 'very dark gray background',
  'bg-gray-900': 'darkest gray background',
  // Background Colors - Blues
  'bg-blue-50': 'lightest blue background',
  'bg-blue-100': 'very light blue background',
  'bg-blue-500': 'blue background',
  'bg-blue-600': 'medium dark blue background',
  'bg-blue-700': 'dark blue background',
  // Background Colors - Other
  'bg-red-500': 'red background',
  'bg-green-500': 'green background',
  'bg-yellow-500': 'yellow background',
  'bg-purple-500': 'purple background',
  'bg-pink-500': 'pink background',
  // Background Attachment
  'bg-fixed': 'fixed background',
  'bg-local': 'local background (scrolls with element)',
  'bg-scroll': 'scrolling background',
  // Background Clip
  'bg-clip-border': 'background includes border',
  'bg-clip-padding': 'background includes padding',
  'bg-clip-content': 'background within content only',
  'bg-clip-text': 'background clips to text',
  // Background Origin
  'bg-origin-border': 'background origin at border',
  'bg-origin-padding': 'background origin at padding',
  'bg-origin-content': 'background origin at content',
  // Background Position
  'bg-top-left': 'background at top left',
  'bg-top': 'background at top',
  'bg-top-right': 'background at top right',
  'bg-left': 'background at left',
  'bg-center': 'background at center',
  'bg-right': 'background at right',
  'bg-bottom-left': 'background at bottom left',
  'bg-bottom': 'background at bottom',
  'bg-bottom-right': 'background at bottom right',
  'bg-left-top': 'background at left top',
  'bg-left-bottom': 'background at left bottom',
  'bg-right-top': 'background at right top',
  'bg-right-bottom': 'background at right bottom',
  // Background Repeat
  'bg-repeat': 'repeating background',
  'bg-no-repeat': 'non-repeating background',
  'bg-repeat-x': 'background repeats horizontally',
  'bg-repeat-y': 'background repeats vertically',
  'bg-repeat-round': 'background repeats and scales to fit',
  'bg-repeat-space': 'background repeats with spacing',
  // Background Size
  'bg-auto': 'auto background size',
  'bg-cover': 'background covers container',
  'bg-contain': 'background contained within element',
  // Background Image
  'bg-none': 'no background image',
  // Linear Gradients (v4 syntax)
  'bg-linear-to-t': 'linear gradient to top',
  'bg-linear-to-tr': 'linear gradient to top right',
  'bg-linear-to-r': 'linear gradient to right',
  'bg-linear-to-br': 'linear gradient to bottom right',
  'bg-linear-to-b': 'linear gradient to bottom',
  'bg-linear-to-bl': 'linear gradient to bottom left',
  'bg-linear-to-l': 'linear gradient to left',
  'bg-linear-to-tl': 'linear gradient to top left',
  'bg-gradient-to-t': 'gradient to top',
  'bg-gradient-to-tr': 'gradient to top right',
  'bg-gradient-to-r': 'gradient to right',
  'bg-gradient-to-br': 'gradient to bottom right',
  'bg-gradient-to-b': 'gradient to bottom',
  'bg-gradient-to-bl': 'gradient to bottom left',
  'bg-gradient-to-l': 'gradient to left',
  'bg-gradient-to-tl': 'gradient to top left',
  // Radial Gradients (v4)
  'bg-radial': 'radial gradient',
  'bg-radial-at-t': 'radial gradient from top',
  'bg-radial-at-tr': 'radial gradient from top right',
  'bg-radial-at-r': 'radial gradient from right',
  'bg-radial-at-br': 'radial gradient from bottom right',
  'bg-radial-at-b': 'radial gradient from bottom',
  'bg-radial-at-bl': 'radial gradient from bottom left',
  'bg-radial-at-l': 'radial gradient from left',
  'bg-radial-at-tl': 'radial gradient from top left',
  'bg-radial-at-c': 'radial gradient from center',
  // Conic Gradients (v4)
  'bg-conic': 'conic gradient',
  'bg-conic-at-t': 'conic gradient from top',
  'bg-conic-at-tr': 'conic gradient from top right',
  'bg-conic-at-r': 'conic gradient from right',
  'bg-conic-at-br': 'conic gradient from bottom right',
  'bg-conic-at-b': 'conic gradient from bottom',
  'bg-conic-at-bl': 'conic gradient from bottom left',
  'bg-conic-at-l': 'conic gradient from left',
  'bg-conic-at-tl': 'conic gradient from top left',
  'bg-conic-at-c': 'conic gradient from center',
  // Gradient Color Stops (base classes, colors handled by patterns)
  'from-inherit': 'gradient starts with inherited color',
  'from-current': 'gradient starts with current color',
  'from-transparent': 'gradient starts with transparent',
  'from-black': 'gradient starts with black',
  'from-white': 'gradient starts with white',
  'via-inherit': 'gradient middle is inherited color',
  'via-current': 'gradient middle is current color',
  'via-transparent': 'gradient middle is transparent',
  'via-black': 'gradient middle is black',
  'via-white': 'gradient middle is white',
  'to-inherit': 'gradient ends with inherited color',
  'to-current': 'gradient ends with current color',
  'to-transparent': 'gradient ends with transparent',
  'to-black': 'gradient ends with black',
  'to-white': 'gradient ends with white',
  // Gradient Color Stop Positions
  'from-0%': 'gradient starts at 0%',
  'from-5%': 'gradient starts at 5%',
  'from-10%': 'gradient starts at 10%',
  'from-15%': 'gradient starts at 15%',
  'from-20%': 'gradient starts at 20%',
  'from-25%': 'gradient starts at 25%',
  'from-30%': 'gradient starts at 30%',
  'from-40%': 'gradient starts at 40%',
  'from-50%': 'gradient starts at 50%',
  'from-60%': 'gradient starts at 60%',
  'from-70%': 'gradient starts at 70%',
  'from-75%': 'gradient starts at 75%',
  'from-80%': 'gradient starts at 80%',
  'from-90%': 'gradient starts at 90%',
  'from-95%': 'gradient starts at 95%',
  'from-100%': 'gradient starts at 100%',
  'via-0%': 'gradient middle at 0%',
  'via-5%': 'gradient middle at 5%',
  'via-10%': 'gradient middle at 10%',
  'via-15%': 'gradient middle at 15%',
  'via-20%': 'gradient middle at 20%',
  'via-25%': 'gradient middle at 25%',
  'via-30%': 'gradient middle at 30%',
  'via-40%': 'gradient middle at 40%',
  'via-50%': 'gradient middle at 50%',
  'via-60%': 'gradient middle at 60%',
  'via-70%': 'gradient middle at 70%',
  'via-75%': 'gradient middle at 75%',
  'via-80%': 'gradient middle at 80%',
  'via-90%': 'gradient middle at 90%',
  'via-95%': 'gradient middle at 95%',
  'via-100%': 'gradient middle at 100%',
  'to-0%': 'gradient ends at 0%',
  'to-5%': 'gradient ends at 5%',
  'to-10%': 'gradient ends at 10%',
  'to-15%': 'gradient ends at 15%',
  'to-20%': 'gradient ends at 20%',
  'to-25%': 'gradient ends at 25%',
  'to-30%': 'gradient ends at 30%',
  'to-40%': 'gradient ends at 40%',
  'to-50%': 'gradient ends at 50%',
  'to-60%': 'gradient ends at 60%',
  'to-70%': 'gradient ends at 70%',
  'to-75%': 'gradient ends at 75%',
  'to-80%': 'gradient ends at 80%',
  'to-90%': 'gradient ends at 90%',
  'to-95%': 'gradient ends at 95%',
  'to-100%': 'gradient ends at 100%',
  // Background Blend Mode
  'bg-blend-normal': 'normal background blend',
  'bg-blend-multiply': 'multiply background blend',
  'bg-blend-screen': 'screen background blend',
  'bg-blend-overlay': 'overlay background blend',
  'bg-blend-darken': 'darken background blend',
  'bg-blend-lighten': 'lighten background blend',
  'bg-blend-color-dodge': 'color dodge background blend',
  'bg-blend-color-burn': 'color burn background blend',
  'bg-blend-hard-light': 'hard light background blend',
  'bg-blend-soft-light': 'soft light background blend',
  'bg-blend-difference': 'difference background blend',
  'bg-blend-exclusion': 'exclusion background blend',
  'bg-blend-hue': 'hue background blend',
  'bg-blend-saturation': 'saturation background blend',
  'bg-blend-color': 'color background blend',
  'bg-blend-luminosity': 'luminosity background blend',
};
