/**
 * Effects: shadow, opacity, blend modes, isolation, masks
 */
export const effectsMappings: Record<string, string> = {
  // Placeholder Color
  'placeholder-transparent': 'transparent placeholder',
  'placeholder-current': 'placeholder matches text color',
  'placeholder-black': 'black placeholder',
  'placeholder-white': 'white placeholder',
  'shadow-2xs': '2x small shadow',
  'shadow-xs': 'extra small shadow',
  'shadow-sm': 'small shadow',
  shadow: 'medium shadow',
  'shadow-md': 'medium shadow',
  'shadow-lg': 'large shadow',
  'shadow-xl': 'extra large shadow',
  'shadow-2xl': '2x large shadow',
  'shadow-none': 'no shadow',
  'shadow-inherit': 'inherited shadow color',
  'shadow-current': 'shadow matches text color',
  'shadow-transparent': 'transparent shadow',
  'shadow-black': 'black shadow',
  'shadow-white': 'white shadow',
  'inset-shadow-2xs': '2x small inset shadow',
  'inset-shadow-xs': 'extra small inset shadow',
  'inset-shadow-sm': 'small inset shadow',
  'inset-shadow-none': 'no inset shadow',
  'inset-shadow-inherit': 'inherited inset shadow color',
  'inset-shadow-current': 'inset shadow matches text color',
  'inset-shadow-transparent': 'transparent inset shadow',
  'inset-shadow-black': 'black inset shadow',
  'inset-shadow-white': 'white inset shadow',
  'text-shadow-2xs': '2x small text shadow',
  'text-shadow-xs': 'extra small text shadow',
  'text-shadow-sm': 'small text shadow',
  'text-shadow': 'medium text shadow',
  'text-shadow-md': 'medium text shadow',
  'text-shadow-lg': 'large text shadow',
  'text-shadow-none': 'no text shadow',
  'text-shadow-inherit': 'inherited text shadow color',
  'text-shadow-current': 'text shadow matches text color',
  'text-shadow-transparent': 'transparent text shadow',
  'text-shadow-black': 'black text shadow',
  'text-shadow-white': 'white text shadow',
  // Isolation
  isolate: 'creates new stacking context',
  'isolation-auto': 'automatic stacking context',
  // Content Visibility (v4)
  'content-visibility-auto': 'auto content visibility (renders when visible)',
  'content-visibility-hidden': 'hides content (skips rendering)',
  'content-visibility-visible': 'always renders content',
  // Containment (v4)
  'contain-none': 'no containment',
  'contain-content': 'contains layout and style',
  'contain-strict': 'strict containment (layout, style, paint, size)',
  'contain-size': 'contains size',
  'contain-layout': 'contains layout',
  'contain-style': 'contains style',
  'contain-paint': 'contains paint',
  // Mask (v4.1)
  mask: 'applies mask',
  'mask-none': 'no mask',
  // Mask Clip
  'mask-clip-border': 'mask clips to border box',
  'mask-clip-padding': 'mask clips to padding box',
  'mask-clip-content': 'mask clips to content box',
  'mask-clip-fill': 'mask clips to fill box',
  'mask-clip-stroke': 'mask clips to stroke box',
  'mask-clip-view': 'mask clips to view box',
  'mask-no-clip': 'mask does not clip',
  // Mask Composite
  'mask-add': 'add mask composite',
  'mask-subtract': 'subtract mask composite',
  'mask-intersect': 'intersect mask composite',
  'mask-exclude': 'exclude mask composite',
  // Mask Radial - Shape
  'mask-circle': 'circular radial mask',
  'mask-ellipse': 'elliptical radial mask',
  // Mask Radial - Size
  'mask-radial-closest-corner': 'radial mask to closest corner',
  'mask-radial-closest-side': 'radial mask to closest side',
  'mask-radial-farthest-corner': 'radial mask to farthest corner',
  'mask-radial-farthest-side': 'radial mask to farthest side',
  // Mask Radial - Position
  'mask-radial-at-top-left': 'radial mask at top left',
  'mask-radial-at-top': 'radial mask at top',
  'mask-radial-at-top-right': 'radial mask at top right',
  'mask-radial-at-left': 'radial mask at left',
  'mask-radial-at-center': 'radial mask at center',
  'mask-radial-at-right': 'radial mask at right',
  'mask-radial-at-bottom-left': 'radial mask at bottom left',
  'mask-radial-at-bottom': 'radial mask at bottom',
  'mask-radial-at-bottom-right': 'radial mask at bottom right',
  // Mask Mode
  'mask-alpha': 'alpha mask mode (opacity determines visibility)',
  'mask-luminance': 'luminance mask mode (brightness determines visibility)',
  'mask-match': 'match source mask mode',
  // Mask Origin
  'mask-origin-border': 'mask positioned relative to border box',
  'mask-origin-padding': 'mask positioned relative to padding box',
  'mask-origin-content': 'mask positioned relative to content box',
  'mask-origin-fill': 'mask positioned relative to fill box',
  'mask-origin-stroke': 'mask positioned relative to stroke box',
  'mask-origin-view': 'mask positioned relative to view box',
  // Mask Position
  'mask-top-left': 'mask at top left',
  'mask-top': 'mask at top',
  'mask-top-right': 'mask at top right',
  'mask-left': 'mask at left',
  'mask-center': 'mask at center',
  'mask-right': 'mask at right',
  'mask-bottom-left': 'mask at bottom left',
  'mask-bottom': 'mask at bottom',
  'mask-bottom-right': 'mask at bottom right',
  // Mask Repeat
  'mask-repeat': 'repeating mask',
  'mask-no-repeat': 'non-repeating mask',
  'mask-repeat-x': 'mask repeats horizontally',
  'mask-repeat-y': 'mask repeats vertically',
  'mask-repeat-space': 'mask repeats with spacing',
  'mask-repeat-round': 'mask repeats rounded',
  // Mask Size
  'mask-auto': 'auto mask size',
  'mask-cover': 'mask covers container',
  'mask-contain': 'mask contained in container',
  // Mask Type (SVG)
  'mask-type-alpha': 'SVG mask uses alpha channel',
  'mask-type-luminance': 'SVG mask uses luminance',
  // Mix Blend Mode
  'mix-blend-normal': 'normal blend mode',
  'mix-blend-multiply': 'multiply blend mode',
  'mix-blend-screen': 'screen blend mode',
  'mix-blend-overlay': 'overlay blend mode',
  'mix-blend-darken': 'darken blend mode',
  'mix-blend-lighten': 'lighten blend mode',
  'mix-blend-color-dodge': 'color dodge blend mode',
  'mix-blend-color-burn': 'color burn blend mode',
  'mix-blend-hard-light': 'hard light blend mode',
  'mix-blend-soft-light': 'soft light blend mode',
  'mix-blend-difference': 'difference blend mode',
  'mix-blend-exclusion': 'exclusion blend mode',
  'mix-blend-hue': 'hue blend mode',
  'mix-blend-saturation': 'saturation blend mode',
  'mix-blend-color': 'color blend mode',
  'mix-blend-luminosity': 'luminosity blend mode',
  'mix-blend-plus-darker': 'plus darker blend mode',
  'mix-blend-plus-lighter': 'plus lighter blend mode',
  // Background Blend Mode
  'bg-blend-normal': 'normal background blend',
  'bg-blend-multiply': 'multiply background blend',
  'bg-blend-screen': 'screen background blend',
  'bg-blend-overlay': 'overlay background blend',
  'bg-blend-darken': 'darken background blend',
  'bg-blend-lighten': 'lighten background blend',
  'bg-blend-color-dodge': 'color dodge background blend',
  'bg-blend-color-burn': 'color burn background blend',
  'bg-blend-hard-light': 'hard light background blend',
  'bg-blend-soft-light': 'soft light background blend',
  'bg-blend-difference': 'difference background blend',
  'bg-blend-exclusion': 'exclusion background blend',
  'bg-blend-hue': 'hue background blend',
  'bg-blend-saturation': 'saturation background blend',
  'bg-blend-color': 'color background blend',
  'bg-blend-luminosity': 'luminosity background blend',
  // Opacity
  'opacity-0': 'invisible',
  'opacity-5': '5% opacity',
  'opacity-10': '10% opacity',
  'opacity-15': '15% opacity',
  'opacity-20': '20% opacity',
  'opacity-25': '25% opacity',
  'opacity-30': '30% opacity',
  'opacity-35': '35% opacity',
  'opacity-40': '40% opacity',
  'opacity-45': '45% opacity',
  'opacity-50': '50% opacity',
  'opacity-55': '55% opacity',
  'opacity-60': '60% opacity',
  'opacity-65': '65% opacity',
  'opacity-70': '70% opacity',
  'opacity-75': '75% opacity',
  'opacity-80': '80% opacity',
  'opacity-85': '85% opacity',
  'opacity-90': '90% opacity',
  'opacity-95': '95% opacity',
  'opacity-100': 'fully opaque',
};
