/**
 * Filter utilities: blur, brightness, contrast, etc.
 */
export const filtersMappings: Record<string, string> = {
  // Filters
  filter: "enables filters",
  "filter-none": "disables all filters",
  "blur-none": "no blur",
  "blur-xs": "extra small blur",
  "blur-sm": "small blur",
  blur: "medium blur",
  "blur-md": "medium blur",
  "blur-lg": "large blur",
  "blur-xl": "extra large blur",
  "blur-2xl": "2x large blur",
  "blur-3xl": "3x large blur",
  "brightness-0": "no brightness",
  "brightness-50": "50% brightness",
  "brightness-75": "75% brightness",
  "brightness-90": "90% brightness",
  "brightness-95": "95% brightness",
  "brightness-100": "normal brightness",
  "brightness-105": "105% brightness",
  "brightness-110": "110% brightness",
  "brightness-125": "125% brightness",
  "brightness-150": "150% brightness",
  "brightness-200": "200% brightness",
  "contrast-0": "no contrast",
  "contrast-50": "50% contrast",
  "contrast-75": "75% contrast",
  "contrast-100": "normal contrast",
  "contrast-125": "125% contrast",
  "contrast-150": "150% contrast",
  "contrast-200": "200% contrast",
  "drop-shadow-xs": "extra small drop shadow",
  "drop-shadow-sm": "small drop shadow",
  "drop-shadow": "drop shadow",
  "drop-shadow-md": "medium drop shadow",
  "drop-shadow-lg": "large drop shadow",
  "drop-shadow-xl": "extra large drop shadow",
  "drop-shadow-2xl": "2x large drop shadow",
  "drop-shadow-none": "no drop shadow",
  "drop-shadow-inherit": "drop shadow color inherit",
  "drop-shadow-current": "drop shadow color currentColor",
  "drop-shadow-transparent": "drop shadow color transparent",
  "drop-shadow-black": "drop shadow color black",
  "drop-shadow-white": "drop shadow color white",
  "grayscale-0": "no grayscale",
  grayscale: "grayscale filter",
  "hue-rotate-0": "no hue rotation",
  "hue-rotate-15": "15° hue rotation",
  "hue-rotate-30": "30° hue rotation",
  "hue-rotate-60": "60° hue rotation",
  "hue-rotate-90": "90° hue rotation",
  "hue-rotate-180": "180° hue rotation",
  "-hue-rotate-15": "-15° hue rotation",
  "-hue-rotate-30": "-30° hue rotation",
  "-hue-rotate-60": "-60° hue rotation",
  "-hue-rotate-90": "-90° hue rotation",
  "-hue-rotate-180": "-180° hue rotation",
  "invert-0": "no invert",
  invert: "invert colors",
  "saturate-0": "no saturation",
  "saturate-50": "50% saturation",
  "saturate-100": "normal saturation",
  "saturate-150": "150% saturation",
  "saturate-200": "200% saturation",
  "sepia-0": "no sepia",
  sepia: "sepia filter",
  // Backdrop Filters
  "backdrop-filter": "enables backdrop filters",
  "backdrop-filter-none": "disables all backdrop filters",
  "backdrop-blur-none": "no background blur",
  "backdrop-blur-xs": "extra small background blur",
  "backdrop-blur-sm": "small background blur",
  "backdrop-blur": "blurred background",
  "backdrop-blur-md": "medium background blur",
  "backdrop-blur-lg": "large background blur",
  "backdrop-blur-xl": "extra large background blur",
  "backdrop-blur-2xl": "2x large background blur",
  "backdrop-blur-3xl": "3x large background blur",
  "backdrop-brightness-0": "no backdrop brightness",
  "backdrop-brightness-50": "50% backdrop brightness",
  "backdrop-brightness-75": "75% backdrop brightness",
  "backdrop-brightness-90": "90% backdrop brightness",
  "backdrop-brightness-95": "95% backdrop brightness",
  "backdrop-brightness-100": "normal backdrop brightness",
  "backdrop-brightness-105": "105% backdrop brightness",
  "backdrop-brightness-110": "110% backdrop brightness",
  "backdrop-brightness-125": "125% backdrop brightness",
  "backdrop-brightness-150": "150% backdrop brightness",
  "backdrop-brightness-200": "200% backdrop brightness",
  "backdrop-contrast-0": "no backdrop contrast",
  "backdrop-contrast-50": "50% backdrop contrast",
  "backdrop-contrast-75": "75% backdrop contrast",
  "backdrop-contrast-100": "normal backdrop contrast",
  "backdrop-contrast-125": "125% backdrop contrast",
  "backdrop-contrast-150": "150% backdrop contrast",
  "backdrop-contrast-200": "200% backdrop contrast",
  "backdrop-grayscale-0": "no backdrop grayscale",
  "backdrop-grayscale": "backdrop grayscale",
  "backdrop-invert-0": "no backdrop invert",
  "backdrop-invert": "backdrop invert",
  "backdrop-opacity-0": "transparent backdrop",
  "backdrop-opacity-5": "5% backdrop opacity",
  "backdrop-opacity-10": "10% backdrop opacity",
  "backdrop-opacity-20": "20% backdrop opacity",
  "backdrop-opacity-25": "25% backdrop opacity",
  "backdrop-opacity-30": "30% backdrop opacity",
  "backdrop-opacity-40": "40% backdrop opacity",
  "backdrop-opacity-50": "50% backdrop opacity",
  "backdrop-opacity-60": "60% backdrop opacity",
  "backdrop-opacity-70": "70% backdrop opacity",
  "backdrop-opacity-75": "75% backdrop opacity",
  "backdrop-opacity-80": "80% backdrop opacity",
  "backdrop-opacity-90": "90% backdrop opacity",
  "backdrop-opacity-95": "95% backdrop opacity",
  "backdrop-opacity-100": "full backdrop opacity",
  "backdrop-saturate-0": "no backdrop saturation",
  "backdrop-saturate-50": "50% backdrop saturation",
  "backdrop-saturate-100": "normal backdrop saturation",
  "backdrop-saturate-150": "150% backdrop saturation",
  "backdrop-saturate-200": "200% backdrop saturation",
  "backdrop-sepia-0": "no backdrop sepia",
  "backdrop-sepia": "backdrop sepia",
  "backdrop-hue-rotate-0": "no backdrop hue rotation",
  "backdrop-hue-rotate-15": "15° backdrop hue rotation",
  "backdrop-hue-rotate-30": "30° backdrop hue rotation",
  "backdrop-hue-rotate-60": "60° backdrop hue rotation",
  "backdrop-hue-rotate-90": "90° backdrop hue rotation",
  "backdrop-hue-rotate-180": "180° backdrop hue rotation",
  "-backdrop-hue-rotate-15": "-15° backdrop hue rotation",
  "-backdrop-hue-rotate-30": "-30° backdrop hue rotation",
  "-backdrop-hue-rotate-60": "-60° backdrop hue rotation",
  "-backdrop-hue-rotate-90": "-90° backdrop hue rotation",
  "-backdrop-hue-rotate-180": "-180° backdrop hue rotation",
};
