/**
 * Flexbox and Grid utilities: flex, grid, justify, align, order, gap, space-between
 */
export const flexboxGridMappings: Record<string, string> = {
  // Flexbox Layout
  flex: "flexbox container",
  "flex-row": "horizontal layout",
  "flex-col": "stacks vertically",
  "flex-row-reverse": "reversed horizontal layout",
  "flex-col-reverse": "reversed vertical layout",
  "flex-wrap": "wraps items to next line",
  "flex-wrap-reverse": "wraps items in reverse",
  "flex-nowrap": "prevents wrapping",
  "flex-1": "takes remaining space",
  "flex-auto": "flexible size",
  "flex-initial": "initial flex",
  "flex-none": "inflexible",
  "flex-grow": "can grow",
  "flex-grow-0": "cannot grow",
  "flex-shrink": "can shrink",
  "flex-shrink-0": "cannot shrink",
  grow: "allows item to grow",
  "grow-0": "cannot grow",
  shrink: "can shrink",
  "shrink-0": "cannot shrink",

  // Flex Basis
  "basis-0": "flex basis 0",
  "basis-px": "flex basis 1px",
  "basis-0.5": "flex basis 0.125rem",
  "basis-1": "flex basis 0.25rem",
  "basis-2": "flex basis 0.5rem",
  "basis-3": "flex basis 0.75rem",
  "basis-4": "flex basis 1rem",
  "basis-5": "flex basis 1.25rem",
  "basis-6": "flex basis 1.5rem",
  "basis-8": "flex basis 2rem",
  "basis-10": "flex basis 2.5rem",
  "basis-12": "flex basis 3rem",
  "basis-auto": "auto flex basis",
  "basis-full": "full flex basis",
  "basis-3xs": "3xs flex basis (16rem)",
  "basis-2xs": "2xs flex basis (18rem)",
  "basis-xs": "xs flex basis (20rem)",
  "basis-sm": "small flex basis (24rem)",
  "basis-md": "medium flex basis (28rem)",
  "basis-lg": "large flex basis (32rem)",
  "basis-xl": "xl flex basis (36rem)",
  "basis-2xl": "2xl flex basis (42rem)",
  "basis-3xl": "3xl flex basis (48rem)",
  "basis-4xl": "4xl flex basis (56rem)",
  "basis-5xl": "5xl flex basis (64rem)",
  "basis-6xl": "6xl flex basis (72rem)",
  "basis-7xl": "7xl flex basis (80rem)",
  "basis-1/2": "half flex basis",
  "basis-1/3": "one third flex basis",
  "basis-2/3": "two thirds flex basis",
  "basis-1/4": "quarter flex basis",
  "basis-2/4": "two quarters flex basis",
  "basis-3/4": "three quarters flex basis",
  "basis-1/5": "one fifth flex basis",
  "basis-2/5": "two fifths flex basis",
  "basis-3/5": "three fifths flex basis",
  "basis-4/5": "four fifths flex basis",
  "basis-1/6": "one sixth flex basis",
  "basis-2/6": "two sixths flex basis",
  "basis-3/6": "three sixths flex basis",
  "basis-4/6": "four sixths flex basis",
  "basis-5/6": "five sixths flex basis",
  "basis-1/12": "one twelfth flex basis",
  "basis-2/12": "two twelfths flex basis",
  "basis-3/12": "three twelfths flex basis",
  "basis-4/12": "four twelfths flex basis",
  "basis-5/12": "five twelfths flex basis",
  "basis-6/12": "six twelfths flex basis",
  "basis-7/12": "seven twelfths flex basis",
  "basis-8/12": "eight twelfths flex basis",
  "basis-9/12": "nine twelfths flex basis",
  "basis-10/12": "ten twelfths flex basis",
  "basis-11/12": "eleven twelfths flex basis",

  // Order
  "order-0": "order 0",
  "order-1": "order 1",
  "order-2": "order 2",
  "order-3": "order 3",
  "order-4": "order 4",
  "order-5": "order 5",
  "order-6": "order 6",
  "order-7": "order 7",
  "order-8": "order 8",
  "order-9": "order 9",
  "order-10": "order 10",
  "order-11": "order 11",
  "order-12": "order 12",
  "order-first": "order first (-9999)",
  "order-last": "order last (9999)",
  "order-none": "normal order (0)",

  // Grid
  grid: "grid container",
  "grid-flow-row": "grid flows by row",
  "grid-flow-col": "grid flows by column",
  "grid-flow-dense": "dense grid flow",
  "grid-flow-row-dense": "dense grid flow by row",
  "grid-flow-col-dense": "dense grid flow by column",
  "grid-flow-row-reverse": "grid flows by reversed rows",
  "grid-flow-col-reverse": "grid flows by reversed columns",
  "auto-cols-auto": "auto column width",
  "auto-cols-min": "minimum column width",
  "auto-cols-max": "maximum column width",
  "auto-cols-fr": "fractional column width",
  "auto-rows-auto": "auto row height",
  "auto-rows-min": "minimum row height",
  "auto-rows-max": "maximum row height",
  "auto-rows-fr": "fractional row height",

  // Container Queries
  "@container": "container query context",
  
  "grid-cols-1": "one column",
  "grid-cols-2": "two columns",
  "grid-cols-3": "three columns",
  "grid-cols-4": "four columns",
  "grid-cols-5": "five columns",
  "grid-cols-6": "six columns",
  "grid-cols-7": "seven columns",
  "grid-cols-8": "eight columns",
  "grid-cols-9": "nine columns",
  "grid-cols-10": "ten columns",
  "grid-cols-11": "eleven columns",
  "grid-cols-12": "twelve columns",
  "grid-cols-none": "no column template",
  "grid-cols-subgrid": "subgrid columns",
  "grid-rows-1": "one row",
  "grid-rows-2": "two rows",
  "grid-rows-3": "three rows",
  "grid-rows-4": "four rows",
  "grid-rows-5": "five rows",
  "grid-rows-6": "six rows",
  "grid-rows-7": "seven rows",
  "grid-rows-8": "eight rows",
  "grid-rows-9": "nine rows",
  "grid-rows-10": "ten rows",
  "grid-rows-11": "eleven rows",
  "grid-rows-12": "twelve rows",
  "grid-rows-none": "no row template",
  "grid-rows-subgrid": "subgrid rows",
  "col-auto": "auto column width",
  "col-span-1": "spans 1 column",
  "col-span-2": "spans 2 columns",
  "col-span-3": "spans 3 columns",
  "col-span-4": "spans 4 columns",
  "col-span-5": "spans 5 columns",
  "col-span-6": "spans 6 columns",
  "col-span-7": "spans 7 columns",
  "col-span-8": "spans 8 columns",
  "col-span-9": "spans 9 columns",
  "col-span-10": "spans 10 columns",
  "col-span-11": "spans 11 columns",
  "col-span-12": "spans 12 columns",
  "col-span-full": "spans all columns",
  "col-start-1": "starts at column 1",
  "col-start-2": "starts at column 2",
  "col-start-3": "starts at column 3",
  "col-start-4": "starts at column 4",
  "col-start-5": "starts at column 5",
  "col-start-6": "starts at column 6",
  "col-start-7": "starts at column 7",
  "col-start-8": "starts at column 8",
  "col-start-9": "starts at column 9",
  "col-start-10": "starts at column 10",
  "col-start-11": "starts at column 11",
  "col-start-12": "starts at column 12",
  "col-start-13": "starts at column 13",
  "col-start-auto": "auto column start",
  "col-end-1": "ends at column 1",
  "col-end-2": "ends at column 2",
  "col-end-3": "ends at column 3",
  "col-end-4": "ends at column 4",
  "col-end-5": "ends at column 5",
  "col-end-6": "ends at column 6",
  "col-end-7": "ends at column 7",
  "col-end-8": "ends at column 8",
  "col-end-9": "ends at column 9",
  "col-end-10": "ends at column 10",
  "col-end-11": "ends at column 11",
  "col-end-12": "ends at column 12",
  "col-end-13": "ends at column 13",
  "col-end-auto": "auto column end",
  "row-auto": "auto row height",
  "row-span-1": "spans 1 row",
  "row-span-2": "spans 2 rows",
  "row-span-3": "spans 3 rows",
  "row-span-4": "spans 4 rows",
  "row-span-5": "spans 5 rows",
  "row-span-6": "spans 6 rows",
  "row-span-7": "spans 7 rows",
  "row-span-8": "spans 8 rows",
  "row-span-9": "spans 9 rows",
  "row-span-10": "spans 10 rows",
  "row-span-11": "spans 11 rows",
  "row-span-12": "spans 12 rows",
  "row-span-full": "spans all rows",
  "row-start-1": "starts at row 1",
  "row-start-2": "starts at row 2",
  "row-start-3": "starts at row 3",
  "row-start-4": "starts at row 4",
  "row-start-5": "starts at row 5",
  "row-start-6": "starts at row 6",
  "row-start-7": "starts at row 7",
  "row-start-8": "starts at row 8",
  "row-start-9": "starts at row 9",
  "row-start-10": "starts at row 10",
  "row-start-11": "starts at row 11",
  "row-start-12": "starts at row 12",
  "row-start-13": "starts at row 13",
  "row-start-auto": "auto row start",
  "row-end-1": "ends at row 1",
  "row-end-2": "ends at row 2",
  "row-end-3": "ends at row 3",
  "row-end-4": "ends at row 4",
  "row-end-5": "ends at row 5",
  "row-end-6": "ends at row 6",
  "row-end-7": "ends at row 7",
  "row-end-8": "ends at row 8",
  "row-end-9": "ends at row 9",
  "row-end-10": "ends at row 10",
  "row-end-11": "ends at row 11",
  "row-end-12": "ends at row 12",
  "row-end-13": "ends at row 13",
  "row-end-auto": "auto row end",

  // Justify Content
  "justify-start": "aligns items to start",
  "justify-end": "aligns items to end",
  "justify-end-safe": "safely aligns items to end",
  "justify-center": "centers items horizontally",
  "justify-center-safe": "safely centers items",
  "justify-between": "spreads items apart",
  "justify-around": "distributes space around items",
  "justify-evenly": "distributes space evenly",
  "justify-stretch": "stretches items to fill",
  "justify-baseline": "aligns items to baseline",
  "justify-normal": "normal justify behavior",

  // Justify Items (grid)
  "justify-items-start": "aligns grid items to start",
  "justify-items-end": "aligns grid items to end",
  "justify-items-end-safe": "safely aligns grid items to end",
  "justify-items-center": "centers grid items",
  "justify-items-center-safe": "safely centers grid items",
  "justify-items-stretch": "stretches grid items",
  "justify-items-normal": "normal justify items behavior",

  // Justify Self
  "justify-self-auto": "auto justify alignment",
  "justify-self-start": "aligns self to start",
  "justify-self-center": "centers self",
  "justify-self-center-safe": "safely centers self",
  "justify-self-end": "aligns self to end",
  "justify-self-end-safe": "safely aligns self to end",
  "justify-self-stretch": "stretches self",

  // Align Content
  "content-normal": "normal content alignment",
  "content-center": "centers content",
  "content-start": "aligns content to start",
  "content-end": "aligns content to end",
  "content-between": "spreads content apart",
  "content-around": "distributes space around content",
  "content-evenly": "distributes content evenly",
  "content-baseline": "aligns content to baseline",
  "content-stretch": "stretches content",

  // Align Items
  "items-start": "aligns items to top",
  "items-end": "aligns items to bottom",
  "items-end-safe": "safely aligns items to bottom",
  "items-center": "centers items vertically",
  "items-center-safe": "safely centers items vertically",
  "items-baseline": "aligns items to baseline",
  "items-baseline-last": "aligns items to last baseline",
  "items-stretch": "stretches items to fill",

  // Align Self
  "self-auto": "auto self alignment",
  "self-start": "aligns self to start",
  "self-end": "aligns self to end",
  "self-end-safe": "safely aligns self to end",
  "self-center": "centers self",
  "self-center-safe": "safely centers self",
  "self-stretch": "stretches self",
  "self-baseline": "aligns self to baseline",
  "self-baseline-last": "aligns self to last baseline",

  // Place Content (grid)
  "place-content-center": "centers content in both axes",
  "place-content-center-safe": "safely centers content in both axes",
  "place-content-start": "aligns content to start in both axes",
  "place-content-end": "aligns content to end in both axes",
  "place-content-end-safe": "safely aligns content to end in both axes",
  "place-content-between": "spreads content in both axes",
  "place-content-around": "distributes space around in both axes",
  "place-content-evenly": "distributes evenly in both axes",
  "place-content-baseline": "aligns to baseline in both axes",
  "place-content-stretch": "stretches in both axes",

  // Place Items (grid)
  "place-items-start": "aligns items to start in both axes",
  "place-items-end": "aligns items to end in both axes",
  "place-items-end-safe": "safely aligns items to end in both axes",
  "place-items-center": "centers items in both axes",
  "place-items-center-safe": "safely centers items in both axes",
  "place-items-baseline": "aligns items to baseline in both axes",
  "place-items-stretch": "stretches items in both axes",

  // Place Self (grid)
  "place-self-auto": "auto placement in both axes",
  "place-self-start": "aligns self to start in both axes",
  "place-self-end": "aligns self to end in both axes",
  "place-self-end-safe": "safely aligns self to end in both axes",
  "place-self-center": "centers self in both axes",
  "place-self-center-safe": "safely centers self in both axes",
  "place-self-stretch": "stretches self in both axes",

  // Gap
  "gap-0": "no gap",
  "gap-px": "gap 1px",
  "gap-0.5": "gap 0.125rem",
  "gap-1": "gap 0.25rem",
  "gap-1.5": "gap 0.375rem",
  "gap-2": "gap 0.5rem",
  "gap-2.5": "gap 0.625rem",
  "gap-3": "gap 0.75rem",
  "gap-3.5": "gap 0.875rem",
  "gap-4": "gap 1rem",
  "gap-5": "gap 1.25rem",
  "gap-6": "gap 1.5rem",
  "gap-7": "gap 1.75rem",
  "gap-8": "gap 2rem",
  "gap-9": "gap 2.25rem",
  "gap-10": "gap 2.5rem",
  "gap-11": "gap 2.75rem",
  "gap-12": "gap 3rem",
  "gap-14": "gap 3.5rem",
  "gap-16": "gap 4rem",
  "gap-x-0": "no horizontal gap",
  "gap-x-px": "horizontal gap 1px",
  "gap-x-0.5": "horizontal gap 0.125rem",
  "gap-x-1": "horizontal gap 0.25rem",
  "gap-x-2": "horizontal gap 0.5rem",
  "gap-x-3": "horizontal gap 0.75rem",
  "gap-x-4": "horizontal gap 1rem",
  "gap-x-6": "horizontal gap 1.5rem",
  "gap-x-8": "horizontal gap 2rem",
  "gap-y-0": "no vertical gap",
  "gap-y-px": "vertical gap 1px",
  "gap-y-0.5": "vertical gap 0.125rem",
  "gap-y-1": "vertical gap 0.25rem",
  "gap-y-2": "vertical gap 0.5rem",
  "gap-y-3": "vertical gap 0.75rem",
  "gap-y-4": "vertical gap 1rem",
  "gap-y-6": "vertical gap 1.5rem",
  "gap-y-8": "vertical gap 2rem",

  // Space Between
  "space-x-0": "no horizontal space between",
  "space-x-px": "1px horizontal space between",
  "space-x-0.5": "0.125rem horizontal space between",
  "space-x-1": "0.25rem horizontal space between",
  "space-x-2": "0.5rem horizontal space between",
  "space-x-3": "0.75rem horizontal space between",
  "space-x-4": "1rem horizontal space between",
  "space-x-6": "1.5rem horizontal space between",
  "space-x-8": "2rem horizontal space between",
  "space-x-reverse": "reversed horizontal space",
  "space-y-0": "no vertical space between",
  "space-y-px": "1px vertical space between",
  "space-y-0.5": "0.125rem vertical space between",
  "space-y-1": "0.25rem vertical space between",
  "space-y-2": "0.5rem vertical space between",
  "space-y-3": "0.75rem vertical space between",
  "space-y-4": "1rem vertical space between",
  "space-y-6": "1.5rem vertical space between",
  "space-y-8": "2rem vertical space between",
  "space-y-reverse": "reversed vertical space",
};

