/**
 * Positioning utilities: top, right, bottom, left, inset, start, end
 */
export const positioningMappings: Record<string, string> = {
  // Position Values
  "top-0": "positioned at top edge",
  "top-px": "top position 1px",
  "top-0.5": "top position 0.125rem",
  "top-1": "top position 0.25rem",
  "top-2": "top position 0.5rem",
  "top-3": "top position 0.75rem",
  "top-4": "top position 1rem",
  "top-5": "top position 1.25rem",
  "top-6": "top position 1.5rem",
  "top-8": "top position 2rem",
  "top-10": "top position 2.5rem",
  "top-12": "top position 3rem",
  "top-16": "top position 4rem",
  "top-20": "top position 5rem",
  "top-24": "top position 6rem",
  "top-32": "top position 8rem",
  "top-40": "top position 10rem",
  "top-48": "top position 12rem",
  "top-56": "top position 14rem",
  "top-64": "top position 16rem",
  "top-1/2": "top position 50%",
  "top-1/3": "top position 33.333%",
  "top-2/3": "top position 66.666%",
  "top-1/4": "top position 25%",
  "top-2/4": "top position 50%",
  "top-3/4": "top position 75%",
  "top-full": "top position 100%",
  "top-auto": "auto top position",
  "right-0": "positioned at right edge",
  "right-px": "right position 1px",
  "right-0.5": "right position 0.125rem",
  "right-1": "right position 0.25rem",
  "right-2": "right position 0.5rem",
  "right-3": "right position 0.75rem",
  "right-4": "right position 1rem",
  "right-5": "right position 1.25rem",
  "right-6": "right position 1.5rem",
  "right-8": "right position 2rem",
  "right-10": "right position 2.5rem",
  "right-12": "right position 3rem",
  "right-16": "right position 4rem",
  "right-20": "right position 5rem",
  "right-24": "right position 6rem",
  "right-32": "right position 8rem",
  "right-40": "right position 10rem",
  "right-48": "right position 12rem",
  "right-56": "right position 14rem",
  "right-64": "right position 16rem",
  "right-1/2": "right position 50%",
  "right-1/3": "right position 33.333%",
  "right-2/3": "right position 66.666%",
  "right-1/4": "right position 25%",
  "right-2/4": "right position 50%",
  "right-3/4": "right position 75%",
  "right-full": "right position 100%",
  "right-auto": "auto right position",
  "bottom-0": "positioned at bottom edge",
  "bottom-px": "bottom position 1px",
  "bottom-0.5": "bottom position 0.125rem",
  "bottom-1": "bottom position 0.25rem",
  "bottom-2": "bottom position 0.5rem",
  "bottom-3": "bottom position 0.75rem",
  "bottom-4": "bottom position 1rem",
  "bottom-5": "bottom position 1.25rem",
  "bottom-6": "bottom position 1.5rem",
  "bottom-8": "bottom position 2rem",
  "bottom-10": "bottom position 2.5rem",
  "bottom-12": "bottom position 3rem",
  "bottom-16": "bottom position 4rem",
  "bottom-20": "bottom position 5rem",
  "bottom-24": "bottom position 6rem",
  "bottom-32": "bottom position 8rem",
  "bottom-40": "bottom position 10rem",
  "bottom-48": "bottom position 12rem",
  "bottom-56": "bottom position 14rem",
  "bottom-64": "bottom position 16rem",
  "bottom-1/2": "bottom position 50%",
  "bottom-1/3": "bottom position 33.333%",
  "bottom-2/3": "bottom position 66.666%",
  "bottom-1/4": "bottom position 25%",
  "bottom-2/4": "bottom position 50%",
  "bottom-3/4": "bottom position 75%",
  "bottom-full": "bottom position 100%",
  "bottom-auto": "auto bottom position",
  "left-0": "positioned at left edge",
  "left-px": "left position 1px",
  "left-0.5": "left position 0.125rem",
  "left-1": "left position 0.25rem",
  "left-2": "left position 0.5rem",
  "left-3": "left position 0.75rem",
  "left-4": "left position 1rem",
  "left-5": "left position 1.25rem",
  "left-6": "left position 1.5rem",
  "left-8": "left position 2rem",
  "left-10": "left position 2.5rem",
  "left-12": "left position 3rem",
  "left-16": "left position 4rem",
  "left-20": "left position 5rem",
  "left-24": "left position 6rem",
  "left-32": "left position 8rem",
  "left-40": "left position 10rem",
  "left-48": "left position 12rem",
  "left-56": "left position 14rem",
  "left-64": "left position 16rem",
  "left-1/2": "left position 50%",
  "left-1/3": "left position 33.333%",
  "left-2/3": "left position 66.666%",
  "left-1/4": "left position 25%",
  "left-2/4": "left position 50%",
  "left-3/4": "left position 75%",
  "left-full": "left position 100%",
  "left-auto": "auto left position",
  "inset-0": "positioned at all edges",
  "inset-px": "inset 1px",
  "inset-0.5": "inset 0.125rem",
  "inset-1": "inset 0.25rem",
  "inset-2": "inset 0.5rem",
  "inset-3": "inset 0.75rem",
  "inset-4": "inset 1rem",
  "inset-5": "inset 1.25rem",
  "inset-6": "inset 1.5rem",
  "inset-8": "inset 2rem",
  "inset-10": "inset 2.5rem",
  "inset-12": "inset 3rem",
  "inset-16": "inset 4rem",
  "inset-20": "inset 5rem",
  "inset-24": "inset 6rem",
  "inset-32": "inset 8rem",
  "inset-40": "inset 10rem",
  "inset-48": "inset 12rem",
  "inset-56": "inset 14rem",
  "inset-64": "inset 16rem",
  "inset-1/2": "inset 50%",
  "inset-1/3": "inset 33.333%",
  "inset-2/3": "inset 66.666%",
  "inset-1/4": "inset 25%",
  "inset-2/4": "inset 50%",
  "inset-3/4": "inset 75%",
  "inset-full": "inset 100%",
  "inset-auto": "auto positioning on all sides",
  "inset-x-0": "left & right at 0",
  "inset-x-px": "left & right at 1px",
  "inset-x-0.5": "left & right at 0.125rem",
  "inset-x-1": "left & right at 0.25rem",
  "inset-x-2": "left & right at 0.5rem",
  "inset-x-3": "left & right at 0.75rem",
  "inset-x-4": "left & right at 1rem",
  "inset-x-5": "left & right at 1.25rem",
  "inset-x-6": "left & right at 1.5rem",
  "inset-x-8": "left & right at 2rem",
  "inset-x-10": "left & right at 2.5rem",
  "inset-x-12": "left & right at 3rem",
  "inset-x-16": "left & right at 4rem",
  "inset-x-20": "left & right at 5rem",
  "inset-x-24": "left & right at 6rem",
  "inset-x-32": "left & right at 8rem",
  "inset-x-40": "left & right at 10rem",
  "inset-x-48": "left & right at 12rem",
  "inset-x-56": "left & right at 14rem",
  "inset-x-64": "left & right at 16rem",
  "inset-x-1/2": "horizontally centered (50%)",
  "inset-x-1/3": "left & right at 33.333%",
  "inset-x-2/3": "left & right at 66.666%",
  "inset-x-1/4": "left & right at 25%",
  "inset-x-2/4": "left & right at 50%",
  "inset-x-3/4": "left & right at 75%",
  "inset-x-full": "left & right at 100%",
  "inset-x-auto": "auto left & right positioning",
  "inset-y-0": "top & bottom at 0",
  "inset-y-px": "top & bottom at 1px",
  "inset-y-0.5": "top & bottom at 0.125rem",
  "inset-y-1": "top & bottom at 0.25rem",
  "inset-y-2": "top & bottom at 0.5rem",
  "inset-y-3": "top & bottom at 0.75rem",
  "inset-y-4": "top & bottom at 1rem",
  "inset-y-5": "top & bottom at 1.25rem",
  "inset-y-6": "top & bottom at 1.5rem",
  "inset-y-8": "top & bottom at 2rem",
  "inset-y-10": "top & bottom at 2.5rem",
  "inset-y-12": "top & bottom at 3rem",
  "inset-y-16": "top & bottom at 4rem",
  "inset-y-20": "top & bottom at 5rem",
  "inset-y-24": "top & bottom at 6rem",
  "inset-y-32": "top & bottom at 8rem",
  "inset-y-40": "top & bottom at 10rem",
  "inset-y-48": "top & bottom at 12rem",
  "inset-y-56": "top & bottom at 14rem",
  "inset-y-64": "top & bottom at 16rem",
  "inset-y-1/2": "vertically centered (50%)",
  "inset-y-1/3": "top & bottom at 33.333%",
  "inset-y-2/3": "top & bottom at 66.666%",
  "inset-y-1/4": "top & bottom at 25%",
  "inset-y-2/4": "top & bottom at 50%",
  "inset-y-3/4": "top & bottom at 75%",
  "inset-y-full": "top & bottom at 100%",
  "inset-y-auto": "auto top & bottom positioning",
};
