/**
 * Transform utilities: scale, rotate, translate, skew, etc.
 */
export const transformsMappings: Record<string, string> = {
  // Transform Scale
  "scale-none": "no scale",
  "scale-0": "scale to 0%",
  "scale-25": "scale to 25%",
  "scale-50": "scale to 50%",
  "scale-75": "scale to 75%",
  "scale-90": "scale to 90%",
  "scale-95": "scale to 95%",
  "scale-100": "scale to 100%",
  "scale-105": "scale to 105%",
  "scale-110": "scale to 110%",
  "scale-125": "scale to 125%",
  "scale-150": "scale to 150%",
  "scale-x-0": "scale horizontally to 0%",
  "scale-x-25": "scale horizontally to 25%",
  "scale-x-50": "scale horizontally to 50%",
  "scale-x-75": "scale horizontally to 75%",
  "scale-x-90": "scale horizontally to 90%",
  "scale-x-95": "scale horizontally to 95%",
  "scale-x-100": "scale horizontally to 100%",
  "scale-x-105": "scale horizontally to 105%",
  "scale-x-110": "scale horizontally to 110%",
  "scale-x-125": "scale horizontally to 125%",
  "scale-x-150": "scale horizontally to 150%",
  "scale-y-0": "scale vertically to 0%",
  "scale-y-25": "scale vertically to 25%",
  "scale-y-50": "scale vertically to 50%",
  "scale-y-75": "scale vertically to 75%",
  "scale-y-90": "scale vertically to 90%",
  "scale-y-95": "scale vertically to 95%",
  "scale-y-100": "scale vertically to 100%",
  "scale-y-105": "scale vertically to 105%",
  "scale-y-110": "scale vertically to 110%",
  "scale-y-125": "scale vertically to 125%",
  "scale-y-150": "scale vertically to 150%",
  // 3D Transform Scale Z (v4)
  "scale-z-0": "scale on Z axis to 0%",
  "scale-z-25": "scale on Z axis to 25%",
  "scale-z-50": "scale on Z axis to 50%",
  "scale-z-75": "scale on Z axis to 75%",
  "scale-z-90": "scale on Z axis to 90%",
  "scale-z-95": "scale on Z axis to 95%",
  "scale-z-100": "scale on Z axis to 100%",
  "scale-z-105": "scale on Z axis to 105%",
  "scale-z-110": "scale on Z axis to 110%",
  "scale-z-125": "scale on Z axis to 125%",
  "scale-z-150": "scale on Z axis to 150%",
  "scale-3d": "3D scale transform",
  // Transform Rotate
  "rotate-none": "no rotation",
  "rotate-0": "rotate 0°",
  "rotate-1": "rotate 1°",
  "rotate-2": "rotate 2°",
  "rotate-3": "rotate 3°",
  "rotate-6": "rotate 6°",
  "rotate-12": "rotate 12°",
  "rotate-45": "rotate 45°",
  "rotate-90": "rotate 90°",
  "rotate-180": "rotate 180°",
  "-rotate-1": "rotate -1°",
  "-rotate-2": "rotate -2°",
  "-rotate-3": "rotate -3°",
  "-rotate-6": "rotate -6°",
  "-rotate-12": "rotate -12°",
  "-rotate-45": "rotate -45°",
  "-rotate-90": "rotate -90°",
  "-rotate-180": "rotate -180°",
  // 3D Transform Rotate (v4)
  "rotate-x-0": "rotate 0° on X axis",
  "rotate-x-45": "rotate 45° on X axis",
  "rotate-x-90": "rotate 90° on X axis",
  "rotate-x-180": "rotate 180° on X axis",
  "rotate-y-0": "rotate 0° on Y axis",
  "rotate-y-45": "rotate 45° on Y axis",
  "rotate-y-90": "rotate 90° on Y axis",
  "rotate-y-180": "rotate 180° on Y axis",
  "rotate-z-0": "rotate 0° on Z axis",
  "rotate-z-45": "rotate 45° on Z axis",
  "rotate-z-90": "rotate 90° on Z axis",
  "rotate-z-180": "rotate 180° on Z axis",
  "-rotate-x-45": "rotate -45° on X axis",
  "-rotate-x-90": "rotate -90° on X axis",
  "-rotate-x-180": "rotate -180° on X axis",
  "-rotate-y-45": "rotate -45° on Y axis",
  "-rotate-y-90": "rotate -90° on Y axis",
  "-rotate-y-180": "rotate -180° on Y axis",
  "-rotate-z-45": "rotate -45° on Z axis",
  "-rotate-z-90": "rotate -90° on Z axis",
  "-rotate-z-180": "rotate -180° on Z axis",
  // Transform Translate
  "translate-none": "no translation",
  "translate-0": "translate 0 on both axes",
  "translate-px": "translate 1px on both axes",
  "translate-0.5": "translate 0.125rem on both axes",
  "translate-1": "translate 0.25rem on both axes",
  "translate-2": "translate 0.5rem on both axes",
  "translate-4": "translate 1rem on both axes",
  "translate-8": "translate 2rem on both axes",
  "translate-1/2": "translate 50% on both axes",
  "translate-1/3": "translate 33.333% on both axes",
  "translate-2/3": "translate 66.666% on both axes",
  "translate-1/4": "translate 25% on both axes",
  "translate-2/4": "translate 50% on both axes",
  "translate-3/4": "translate 75% on both axes",
  "translate-full": "translate 100% on both axes",
  "-translate-px": "translate -1px on both axes",
  "-translate-0.5": "translate -0.125rem on both axes",
  "-translate-1": "translate -0.25rem on both axes",
  "-translate-2": "translate -0.5rem on both axes",
  "-translate-4": "translate -1rem on both axes",
  "-translate-8": "translate -2rem on both axes",
  "-translate-1/2": "translate -50% on both axes",
  "-translate-1/3": "translate -33.333% on both axes",
  "-translate-2/3": "translate -66.666% on both axes",
  "-translate-1/4": "translate -25% on both axes",
  "-translate-2/4": "translate -50% on both axes",
  "-translate-3/4": "translate -75% on both axes",
  "-translate-full": "translate -100% on both axes",
  "translate-x-0": "translate horizontally 0",
  "translate-x-px": "translate horizontally 1px",
  "translate-x-0.5": "translate horizontally 0.125rem",
  "translate-x-1": "translate horizontally 0.25rem",
  "translate-x-2": "translate horizontally 0.5rem",
  "translate-x-4": "translate horizontally 1rem",
  "translate-x-8": "translate horizontally 2rem",
  "translate-x-1/2": "translate horizontally 50%",
  "translate-x-1/3": "translate horizontally 33.333%",
  "translate-x-2/3": "translate horizontally 66.666%",
  "translate-x-1/4": "translate horizontally 25%",
  "translate-x-2/4": "translate horizontally 50%",
  "translate-x-3/4": "translate horizontally 75%",
  "translate-x-full": "translate horizontally 100%",
  "-translate-x-px": "translate horizontally -1px",
  "-translate-x-0.5": "translate horizontally -0.125rem",
  "-translate-x-1": "translate horizontally -0.25rem",
  "-translate-x-2": "translate horizontally -0.5rem",
  "-translate-x-4": "translate horizontally -1rem",
  "-translate-x-1/2": "translate horizontally -50%",
  "-translate-x-1/3": "translate horizontally -33.333%",
  "-translate-x-2/3": "translate horizontally -66.666%",
  "-translate-x-1/4": "translate horizontally -25%",
  "-translate-x-2/4": "translate horizontally -50%",
  "-translate-x-3/4": "translate horizontally -75%",
  "-translate-x-full": "translate horizontally -100%",
  "translate-y-0": "translate vertically 0",
  "translate-y-px": "translate vertically 1px",
  "translate-y-0.5": "translate vertically 0.125rem",
  "translate-y-1": "translate vertically 0.25rem",
  "translate-y-2": "translate vertically 0.5rem",
  "translate-y-4": "translate vertically 1rem",
  "translate-y-8": "translate vertically 2rem",
  "translate-y-1/2": "translate vertically 50%",
  "translate-y-1/3": "translate vertically 33.333%",
  "translate-y-2/3": "translate vertically 66.666%",
  "translate-y-1/4": "translate vertically 25%",
  "translate-y-2/4": "translate vertically 50%",
  "translate-y-3/4": "translate vertically 75%",
  "translate-y-full": "translate vertically 100%",
  "-translate-y-px": "translate vertically -1px",
  "-translate-y-0.5": "translate vertically -0.125rem",
  "-translate-y-1": "translate vertically -0.25rem",
  "-translate-y-2": "translate vertically -0.5rem",
  "-translate-y-4": "translate vertically -1rem",
  "-translate-y-1/2": "translate vertically -50%",
  "-translate-y-1/3": "translate vertically -33.333%",
  "-translate-y-2/3": "translate vertically -66.666%",
  "-translate-y-1/4": "translate vertically -25%",
  "-translate-y-2/4": "translate vertically -50%",
  "-translate-y-3/4": "translate vertically -75%",
  "-translate-y-full": "translate vertically -100%",
  // 3D Transform Translate Z (v4)
  "translate-z-0": "translate on Z axis 0",
  "translate-z-px": "translate on Z axis 1px",
  "translate-z-0.5": "translate on Z axis 0.125rem",
  "translate-z-1": "translate on Z axis 0.25rem",
  "translate-z-2": "translate on Z axis 0.5rem",
  "translate-z-4": "translate on Z axis 1rem",
  "translate-z-8": "translate on Z axis 2rem",
  "-translate-z-px": "translate on Z axis -1px",
  "-translate-z-0.5": "translate on Z axis -0.125rem",
  "-translate-z-1": "translate on Z axis -0.25rem",
  "-translate-z-2": "translate on Z axis -0.5rem",
  "-translate-z-4": "translate on Z axis -1rem",
  "-translate-z-8": "translate on Z axis -2rem",
  // Transform Skew
  "skew-0": "skew 0° on both axes",
  "skew-1": "skew 1° on both axes",
  "skew-2": "skew 2° on both axes",
  "skew-3": "skew 3° on both axes",
  "skew-6": "skew 6° on both axes",
  "skew-12": "skew 12° on both axes",
  "-skew-1": "skew -1° on both axes",
  "-skew-2": "skew -2° on both axes",
  "-skew-3": "skew -3° on both axes",
  "-skew-6": "skew -6° on both axes",
  "-skew-12": "skew -12° on both axes",
  "skew-x-0": "skew horizontally 0°",
  "skew-x-1": "skew horizontally 1°",
  "skew-x-2": "skew horizontally 2°",
  "skew-x-3": "skew horizontally 3°",
  "skew-x-6": "skew horizontally 6°",
  "skew-x-12": "skew horizontally 12°",
  "-skew-x-1": "skew horizontally -1°",
  "-skew-x-2": "skew horizontally -2°",
  "-skew-x-3": "skew horizontally -3°",
  "-skew-x-6": "skew horizontally -6°",
  "-skew-x-12": "skew horizontally -12°",
  "skew-y-0": "skew vertically 0°",
  "skew-y-1": "skew vertically 1°",
  "skew-y-2": "skew vertically 2°",
  "skew-y-3": "skew vertically 3°",
  "skew-y-6": "skew vertically 6°",
  "skew-y-12": "skew vertically 12°",
  "-skew-y-1": "skew vertically -1°",
  "-skew-y-2": "skew vertically -2°",
  "-skew-y-3": "skew vertically -3°",
  "-skew-y-6": "skew vertically -6°",
  "-skew-y-12": "skew vertically -12°",
  // Transform Origin
  "origin-center": "transform from center",
  "origin-top": "transform from top",
  "origin-top-right": "transform from top right",
  "origin-right": "transform from right",
  "origin-bottom-right": "transform from bottom right",
  "origin-bottom": "transform from bottom",
  "origin-bottom-left": "transform from bottom left",
  "origin-left": "transform from left",
  "origin-top-left": "transform from top left",
  // Perspective (v4)
  "perspective-none": "no perspective",
  "perspective-dramatic": "100px perspective (dramatic)",
  "perspective-near": "300px perspective (near)",
  "perspective-normal": "500px perspective (normal)",
  "perspective-midrange": "800px perspective (midrange)",
  "perspective-distant": "1200px perspective (distant)",
  "perspective-100": "100px perspective",
  "perspective-200": "200px perspective",
  "perspective-300": "300px perspective",
  "perspective-500": "500px perspective",
  "perspective-1000": "1000px perspective",
  // Perspective Origin (v4)
  "perspective-origin-center": "perspective from center",
  "perspective-origin-top": "perspective from top",
  "perspective-origin-top-right": "perspective from top right",
  "perspective-origin-right": "perspective from right",
  "perspective-origin-bottom-right": "perspective from bottom right",
  "perspective-origin-bottom": "perspective from bottom",
  "perspective-origin-bottom-left": "perspective from bottom left",
  "perspective-origin-left": "perspective from left",
  "perspective-origin-top-left": "perspective from top left",
  // Transform Style (v4)
  "transform-style-flat": "flat transform style (2D)",
  "transform-style-3d": "3D transform style",
  "transform-flat": "flat transform style (2D)",
  "transform-3d": "3D transform style (preserve-3d)",
  // Transform
  "transform-none": "no transforms",
  "transform-gpu": "GPU-accelerated transform",
  "transform-cpu": "CPU-based transform",
  // Backface Visibility
  "backface-visible": "backface is visible when rotated",
  "backface-hidden": "backface is hidden when rotated",
};
