/**
 * Central export point for all test cases
 * Import test cases from here to keep imports clean and organized
 * 
 * @example
 * import { CATEGORIZE_LAYOUT_CASES, MATCHER_SPACING_CASES } from '@tests/_support/cases';
 */

// Categorizer test cases
export {
  CATEGORIZE_LAYOUT_CASES,
  CATEGORIZE_FLEX_CASES,
  CATEGORIZE_GRID_CASES,
  CATEGORIZE_COLORS_TEXT_CASES,
  CATEGORIZE_COLORS_BORDER_CASES,
  CATEGORIZE_COLORS_RING_CASES,
  CATEGORIZE_BACKGROUNDS_COLOR_CASES,
  CATEGORIZE_BACKGROUNDS_GRADIENT_CASES,
  CATEGORIZE_BORDERS_WIDTH_CASES,
  CATEGORIZE_BORDERS_RADIUS_CASES,
  CATEGORIZE_BORDERS_STYLE_CASES,
  CATEGORIZE_TYPOGRAPHY_SIZE_CASES,
  CATEGORIZE_TYPOGRAPHY_WEIGHT_CASES,
  CATEGORIZE_TYPOGRAPHY_ALIGN_CASES,
  CATEGORIZE_TYPOGRAPHY_LINE_CASES,
  CATEGORIZE_TRANSFORMS_CASES,
  CATEGORIZE_TRANSITIONS_CASES,
  CATEGORIZE_ANIMATION_CASES,
  CATEGORIZE_EFFECTS_SHADOW_CASES,
  CATEGORIZE_EFFECTS_OPACITY_CASES,
  CATEGORIZE_SPACING_PADDING_CASES,
  CATEGORIZE_SPACING_MARGIN_CASES,
  CATEGORIZE_SPACING_SPACE_BETWEEN_CASES,
  CATEGORIZE_SIZING_WIDTH_CASES,
  CATEGORIZE_SIZING_HEIGHT_CASES,
  CATEGORIZE_SIZING_SIZE_CASES,
  CATEGORIZE_VARIANTS_STRIP_CASES,
  CATEGORIZE_VARIANTS_MULTIPLE_CASES,
  CATEGORIZE_UNKNOWN_CASES,
  CATEGORY_NAMES,
  GROUP_BY_CATEGORY_BASIC_CASE,
  GROUP_SAME_CATEGORY_CASE,
  GROUP_WITH_VARIANTS_CASE,
  GROUP_EMOJI_CASE,
  GROUP_NO_EMOJI_CASE,
  GROUP_CATEGORY_ORDER_CASE,
} from './categorizer';

// Matcher test cases
export {
  MATCHER_SPACING_CASES,
  MATCHER_SIZING_CASES,
  MATCHER_COLOR_SCALE_CASES,
  MATCHER_BORDER_CASES,
  MATCHER_TYPOGRAPHY_CASES,
  MATCHER_GRID_CASES,
  MATCHER_TRANSFORM_CASES,
  MATCHER_OPACITY_CASES,
  MATCHER_SHADOW_CASES,
  MATCHER_ARBITRARY_WIDTH_CASES,
  MATCHER_ARBITRARY_SPACING_CASES,
  MATCHER_ARBITRARY_COLOR_CASES,
  MATCHER_CSS_VAR_CASES,
  MATCHER_CQ_UNITS_CASES,
  MATCHER_VIEWPORT_UNITS_CASES,
  MATCHER_UNKNOWN_CASES,
} from './matchers';

// Pattern test cases
export {
  SPACING_DIRECTIONAL_CASES,
  MARGIN_DIRECTIONAL_CASES,
  SPACING_AXIS_CASES,
  SPACING_NEGATIVE_CASES,
  SPACING_NUMERIC_PADDING_CASES,
  SPACING_NUMERIC_MARGIN_CASES,
  SPACING_AUTO_CASES,
  GRID_COLS_CASES,
  GRID_ROWS_CASES,
  SIZING_SIZE_PATTERN_CASES,
  COLOR_TEXT_NUMERIC_CASES,
  COLOR_BG_NUMERIC_CASES,
  COLOR_BORDER_NUMERIC_CASES,
  OPACITY_CASES,
  TRANSFORM_SCALE_CASES,
  TRANSFORM_ROTATE_CASES,
  TRANSFORM_TRANSLATE_CASES,
  GAP_NUMERIC_CASES,
  GAP_AXIS_CASES,
  SHADOW_NAMED_CASES,
  FONT_SIZE_NAMED_CASES,
  BORDER_RADIUS_NAMED_CASES,
  NON_SPACING_CASES,
  NON_SIZING_CASES,
  NON_COLOR_WITH_SCALE_CASES,
  NON_ARBITRARY_CASES,
  NON_GAP_CASES,
  NON_OPACITY_CASES,
} from './patterns';

// Arbitrary value test cases
export {
  ARBITRARY_WIDTH_CASES,
  ARBITRARY_HEIGHT_CASES,
  ARBITRARY_SPACING_CASES,
  ARBITRARY_COLOR_CASES,
  ARBITRARY_BG_COLOR_CASES,
  ARBITRARY_TEXT_COLOR_CASES,
  IS_CSS_VARIABLE_CASES,
  TRANSLATE_CSS_VARIABLE_CASES,
  IS_ARBITRARY_PROPERTY_CASES,
  DESCRIBE_ARBITRARY_PROPERTY_CASES,
  TRANSLATE_ARBITRARY_PROPERTY_CASES,
  EMPTY_STRING_PATTERNS,
  MALFORMED_ARBITRARY_CASES,
  UNICODE_ARBITRARY_CASES,
} from './arbitrary';

// Variant test cases
export {
  VARIANT_CASES,
  VARIANT_INTERACTION_CASES,
  VARIANT_RESPONSIVE_CASES,
  VARIANT_DARK_MODE_CASES,
  VARIANT_PSEUDO_ELEMENT_CASES,
  VARIANT_GROUP_CASES,
  VARIANT_PEER_CASES,
  APPLY_VARIANTS_CASES,
  DESCRIBE_ARBITRARY_VARIANT_CASES,
} from './variants';

// Modifier test cases
export {
  APPLY_OPACITY_CASES,
  APPLY_OPACITY_COMPLEX_CASES,
  INVALID_OPACITY_CASES,
  FULL_MODIFIER_CHAIN_CASES,
  REAL_WORLD_COMPLEX_CASES,
  MALFORMED_MODIFIER_CASES,
} from './modifiers';

// Parser test cases
export {
  BRACKET_EDGE_CASES,
  PARSE_SPLIT_CASES,
  EXTRACT_VARIANTS_CASES,
  COMPLEX_VARIANT_EXTRACTION_CASES,
  EXTRACT_IMPORTANT_CASES,
  IMPORTANT_EXTRACTION_EDGE_CASES,
  EXTRACT_PREFIX_CASES,
  PREFIX_EXTRACTION_EDGE_CASES,
  OPACITY_EXTRACTION_EDGE_CASES,
} from './parser';

// Static mapping test cases
export {
  TRANSLATE_STATIC_CASES,
  CATEGORY_ORDER,
} from './static-mappings';

// Edge case and performance test cases
export {
  GRACEFUL_DEGRADATION_CASES,
  PERFORMANCE_CASES,
} from './edge-cases';

