// Tailwind class to plain English mappings
export const tailwindMappings: Record<string, string> = {
  // Display
  block: "display as block",
  "inline-block": "display as inline block",
  inline: "display inline",
  "inline-flex": "inline flex container",
  "inline-grid": "inline grid container",
  table: "display as table",
  "inline-table": "display as inline table",
  "table-caption": "display as table caption",
  "table-cell": "display as table cell",
  "table-column": "display as table column",
  "table-column-group": "display as table column group",
  "table-footer-group": "display as table footer group",
  "table-header-group": "display as table header group",
  "table-row-group": "display as table row group",
  "table-row": "display as table row",
  "flow-root": "flow-root display",
  contents: "contents only (no box)",
  "list-item": "display as list item",
  hidden: "not visible",

  // Visibility
  visible: "visible",
  invisible: "hidden but takes up space",
  collapse: "collapses table rows/columns",

  // Float
  "float-start": "floats to start side",
  "float-end": "floats to end side",
  "float-right": "floats to right",
  "float-left": "floats to left",
  "float-none": "no float",

  // Clear
  "clear-start": "clears start side floats",
  "clear-end": "clears end side floats",
  "clear-left": "clears left floats",
  "clear-right": "clears right floats",
  "clear-both": "clears both side floats",
  "clear-none": "no clear",

  // Box Sizing
  "box-border": "includes border and padding in size",
  "box-content": "excludes border and padding from size",

  // Object Fit
  "object-contain": "scales to fit while maintaining aspect ratio",
  "object-cover": "covers container while maintaining aspect ratio",
  "object-fill": "stretches to fill container",
  "object-none": "not resized",
  "object-scale-down": "scales down to fit (contain or none)",

  // Object Position
  "object-bottom": "positions content at bottom",
  "object-center": "positions content at center",
  "object-left": "positions content at left",
  "object-left-bottom": "positions content at left bottom",
  "object-left-top": "positions content at left top",
  "object-right": "positions content at right",
  "object-right-bottom": "positions content at right bottom",
  "object-right-top": "positions content at right top",
  "object-top": "positions content at top",

  // Flexbox Layout
  flex: "flexbox container",
  "flex-row": "horizontal layout",
  "flex-col": "stacks vertically",
  "flex-row-reverse": "reversed horizontal layout",
  "flex-col-reverse": "reversed vertical layout",
  "flex-wrap": "wraps items to next line",
  "flex-wrap-reverse": "wraps items in reverse",
  "flex-nowrap": "prevents wrapping",
  "flex-1": "takes remaining space",
  "flex-auto": "flexible size",
  "flex-initial": "initial flex",
  "flex-none": "inflexible",
  "flex-grow": "can grow",
  "flex-grow-0": "cannot grow",
  "flex-shrink": "can shrink",
  "flex-shrink-0": "cannot shrink",
  grow: "can grow",
  "grow-0": "cannot grow",
  shrink: "can shrink",
  "shrink-0": "cannot shrink",

  // Order
  "order-1": "order 1",
  "order-2": "order 2",
  "order-3": "order 3",
  "order-4": "order 4",
  "order-5": "order 5",
  "order-6": "order 6",
  "order-7": "order 7",
  "order-8": "order 8",
  "order-9": "order 9",
  "order-10": "order 10",
  "order-11": "order 11",
  "order-12": "order 12",
  "order-first": "order first (-9999)",
  "order-last": "order last (9999)",
  "order-none": "normal order (0)",

  // Grid
  grid: "grid container",
  "grid-cols-1": "one column",
  "grid-cols-2": "two columns",
  "grid-cols-3": "three columns",
  "grid-cols-4": "four columns",
  "grid-cols-5": "five columns",
  "grid-cols-6": "six columns",
  "grid-cols-7": "seven columns",
  "grid-cols-8": "eight columns",
  "grid-cols-9": "nine columns",
  "grid-cols-10": "ten columns",
  "grid-cols-11": "eleven columns",
  "grid-cols-12": "twelve columns",
  "grid-cols-none": "no column template",
  "grid-cols-subgrid": "subgrid columns",
  "grid-rows-1": "one row",
  "grid-rows-2": "two rows",
  "grid-rows-3": "three rows",
  "grid-rows-4": "four rows",
  "grid-rows-5": "five rows",
  "grid-rows-6": "six rows",
  "grid-rows-7": "seven rows",
  "grid-rows-8": "eight rows",
  "grid-rows-9": "nine rows",
  "grid-rows-10": "ten rows",
  "grid-rows-11": "eleven rows",
  "grid-rows-12": "twelve rows",
  "grid-rows-none": "no row template",
  "grid-rows-subgrid": "subgrid rows",
  "col-auto": "auto column width",
  "col-span-1": "spans 1 column",
  "col-span-2": "spans 2 columns",
  "col-span-3": "spans 3 columns",
  "col-span-4": "spans 4 columns",
  "col-span-5": "spans 5 columns",
  "col-span-6": "spans 6 columns",
  "col-span-7": "spans 7 columns",
  "col-span-8": "spans 8 columns",
  "col-span-9": "spans 9 columns",
  "col-span-10": "spans 10 columns",
  "col-span-11": "spans 11 columns",
  "col-span-12": "spans 12 columns",
  "col-span-full": "spans all columns",
  "col-start-1": "starts at column 1",
  "col-start-2": "starts at column 2",
  "col-start-3": "starts at column 3",
  "col-start-auto": "auto column start",
  "col-end-1": "ends at column 1",
  "col-end-2": "ends at column 2",
  "col-end-3": "ends at column 3",
  "col-end-auto": "auto column end",
  "row-auto": "auto row height",
  "row-span-1": "spans 1 row",
  "row-span-2": "spans 2 rows",
  "row-span-3": "spans 3 rows",
  "row-span-4": "spans 4 rows",
  "row-span-5": "spans 5 rows",
  "row-span-6": "spans 6 rows",
  "row-span-7": "spans 7 rows",
  "row-span-8": "spans 8 rows",
  "row-span-9": "spans 9 rows",
  "row-span-10": "spans 10 rows",
  "row-span-11": "spans 11 rows",
  "row-span-12": "spans 12 rows",
  "row-span-full": "spans all rows",
  "row-start-1": "starts at row 1",
  "row-start-2": "starts at row 2",
  "row-start-3": "starts at row 3",
  "row-start-auto": "auto row start",
  "row-end-1": "ends at row 1",
  "row-end-2": "ends at row 2",
  "row-end-3": "ends at row 3",
  "row-end-auto": "auto row end",

  // Justify Content
  "justify-start": "aligns items to start",
  "justify-end": "aligns items to end",
  "justify-center": "centers items horizontally",
  "justify-between": "spreads items apart",
  "justify-around": "distributes space around items",
  "justify-evenly": "distributes space evenly",
  "justify-normal": "normal justify behavior",
  "justify-stretch": "stretches items to fill",

  // Justify Items (grid)
  "justify-items-start": "aligns grid items to start",
  "justify-items-end": "aligns grid items to end",
  "justify-items-center": "centers grid items",
  "justify-items-stretch": "stretches grid items",

  // Justify Self
  "justify-self-auto": "auto justify alignment",
  "justify-self-start": "aligns self to start",
  "justify-self-end": "aligns self to end",
  "justify-self-center": "centers self",
  "justify-self-stretch": "stretches self",

  // Align Content
  "content-normal": "normal content alignment",
  "content-center": "centers content",
  "content-start": "aligns content to start",
  "content-end": "aligns content to end",
  "content-between": "spreads content apart",
  "content-around": "distributes space around content",
  "content-evenly": "distributes content evenly",
  "content-baseline": "aligns content to baseline",
  "content-stretch": "stretches content",

  // Align Items
  "items-start": "aligns items to top",
  "items-end": "aligns items to bottom",
  "items-center": "centers items vertically",
  "items-baseline": "aligns items to baseline",
  "items-stretch": "stretches items to fill",

  // Align Self
  "self-auto": "auto self alignment",
  "self-start": "aligns self to start",
  "self-end": "aligns self to end",
  "self-center": "centers self",
  "self-stretch": "stretches self",
  "self-baseline": "aligns self to baseline",

  // Place Content (grid)
  "place-content-center": "centers content in both axes",
  "place-content-start": "aligns content to start in both axes",
  "place-content-end": "aligns content to end in both axes",
  "place-content-between": "spreads content in both axes",
  "place-content-around": "distributes space around in both axes",
  "place-content-evenly": "distributes evenly in both axes",
  "place-content-baseline": "aligns to baseline in both axes",
  "place-content-stretch": "stretches in both axes",

  // Place Items (grid)
  "place-items-start": "aligns items to start in both axes",
  "place-items-end": "aligns items to end in both axes",
  "place-items-center": "centers items in both axes",
  "place-items-baseline": "aligns items to baseline in both axes",
  "place-items-stretch": "stretches items in both axes",

  // Place Self (grid)
  "place-self-auto": "auto placement in both axes",
  "place-self-start": "aligns self to start in both axes",
  "place-self-end": "aligns self to end in both axes",
  "place-self-center": "centers self in both axes",
  "place-self-stretch": "stretches self in both axes",

  // Gap
  "gap-0": "no gap",
  "gap-1": "gap 0.25rem",
  "gap-2": "gap 0.5rem",
  "gap-3": "gap 0.75rem",
  "gap-4": "gap 1rem",
  "gap-5": "gap 1.25rem",
  "gap-6": "gap 1.5rem",
  "gap-8": "gap 2rem",
  "gap-10": "gap 2.5rem",
  "gap-12": "gap 3rem",

  // Padding - All sides
  "p-0": "no padding",
  "p-1": "padding 0.25rem",
  "p-2": "padding 0.5rem",
  "p-3": "padding 0.75rem",
  "p-4": "padding 1rem",
  "p-5": "padding 1.25rem",
  "p-6": "padding 1.5rem",
  "p-8": "padding 2rem",
  "p-10": "padding 2.5rem",
  "p-12": "padding 3rem",

  // Padding - Horizontal/Vertical
  "px-2": "horizontal padding 0.5rem",
  "px-4": "horizontal padding 1rem",
  "px-6": "horizontal padding 1.5rem",
  "px-8": "horizontal padding 2rem",
  "py-2": "vertical padding 0.5rem",
  "py-4": "vertical padding 1rem",
  "py-6": "vertical padding 1.5rem",
  "py-8": "vertical padding 2rem",

  // Padding - Individual sides
  "pt-4": "top padding 1rem",
  "pr-4": "right padding 1rem",
  "pb-4": "bottom padding 1rem",
  "pl-4": "left padding 1rem",

  // Margin - All sides
  "m-0": "no margin",
  "m-auto": "centered with auto margin",
  "m-1": "margin 0.25rem",
  "m-2": "margin 0.5rem",
  "m-4": "margin 1rem",
  "m-6": "margin 1.5rem",
  "m-8": "margin 2rem",

  // Margin - Horizontal/Vertical
  "mx-auto": "horizontally centered",
  "mx-2": "horizontal margin 0.5rem",
  "mx-4": "horizontal margin 1rem",
  "my-2": "vertical margin 0.5rem",
  "my-4": "vertical margin 1rem",

  // Width
  "w-full": "full width",
  "w-screen": "full screen width",
  "w-auto": "auto width",
  "w-1/2": "half width",
  "w-1/3": "one third width",
  "w-2/3": "two thirds width",
  "w-1/4": "quarter width",
  "w-10": "width 2.5rem",
  "w-20": "width 5rem",
  "w-32": "width 8rem",
  "w-64": "width 16rem",

  // Max Width
  "max-w-xs": "max width extra small",
  "max-w-sm": "max width small",
  "max-w-md": "max width medium",
  "max-w-lg": "max width large",
  "max-w-xl": "max width extra large",
  "max-w-2xl": "max width 2xl",
  "max-w-3xl": "max width 3xl",
  "max-w-4xl": "max width 4xl",
  "max-w-5xl": "max width 5xl",
  "max-w-6xl": "max width 6xl",
  "max-w-7xl": "max width 7xl",
  "max-w-full": "max width full",
  "max-w-screen-sm": "max width small screen",
  "max-w-screen-md": "max width medium screen",
  "max-w-screen-lg": "max width large screen",
  "max-w-screen-xl": "max width extra large screen",

  // Height
  "h-full": "full height",
  "h-screen": "full screen height",
  "h-auto": "auto height",
  "h-10": "height 2.5rem",
  "h-20": "height 5rem",
  "h-32": "height 8rem",
  "h-64": "height 16rem",
  "min-h-screen": "minimum screen height",
  "min-h-full": "minimum full height",

  // Aspect Ratio
  "aspect-auto": "automatic aspect ratio",
  "aspect-square": "square aspect ratio (1:1)",
  "aspect-video": "video aspect ratio (16:9)",

  // Background Colors - Grays
  "bg-white": "white background",
  "bg-black": "black background",
  "bg-transparent": "transparent background",
  "bg-gray-50": "lightest gray background",
  "bg-gray-100": "very light gray background",
  "bg-gray-200": "light gray background",
  "bg-gray-300": "lightish gray background",
  "bg-gray-400": "medium light gray background",
  "bg-gray-500": "medium gray background",
  "bg-gray-600": "medium dark gray background",
  "bg-gray-700": "dark gray background",
  "bg-gray-800": "very dark gray background",
  "bg-gray-900": "darkest gray background",

  // Background Colors - Blues
  "bg-blue-50": "lightest blue background",
  "bg-blue-100": "very light blue background",
  "bg-blue-500": "blue background",
  "bg-blue-600": "medium dark blue background",
  "bg-blue-700": "dark blue background",

  // Background Colors - Other
  "bg-red-500": "red background",
  "bg-green-500": "green background",
  "bg-yellow-500": "yellow background",
  "bg-purple-500": "purple background",
  "bg-pink-500": "pink background",

  // Text Colors - Grays
  "text-white": "white text",
  "text-black": "black text",
  "text-gray-50": "lightest gray text",
  "text-gray-100": "very light gray text",
  "text-gray-400": "medium light gray text",
  "text-gray-500": "medium gray text",
  "text-gray-600": "medium dark gray text",
  "text-gray-700": "dark gray text",
  "text-gray-800": "very dark gray text",
  "text-gray-900": "darkest gray text",

  // Text Colors - Other
  "text-blue-500": "blue text",
  "text-blue-600": "medium dark blue text",
  "text-red-500": "red text",
  "text-green-500": "green text",

  // Text Size
  "text-xs": "extra small text",
  "text-sm": "small text",
  "text-base": "base text size",
  "text-lg": "large text",
  "text-xl": "extra large text",
  "text-2xl": "2x large text",
  "text-3xl": "3x large text",
  "text-4xl": "4x large text",
  "text-5xl": "5x large text",
  "text-6xl": "6x large text",
  "text-7xl": "7x large text",
  "text-8xl": "8x large text",
  "text-9xl": "9x large text",

  // Text Alignment
  "text-left": "left aligned text",
  "text-center": "center aligned text",
  "text-right": "right aligned text",
  "text-justify": "justified text",

  // Text Overflow
  truncate: "cuts off text with ellipsis (...)",
  "text-ellipsis": "shows ellipsis for overflow",
  "text-clip": "clips overflow text",

  // Font Weight
  "font-thin": "thin weight",
  "font-extralight": "extra light weight",
  "font-light": "light weight",
  "font-normal": "normal weight",
  "font-medium": "medium weight",
  "font-semibold": "semi-bold weight",
  "font-bold": "bold weight",
  "font-extrabold": "extra bold weight",
  "font-black": "black weight",

  // Font Style
  italic: "italic text",
  "not-italic": "not italic",

  // Leading (Line Height)
  "leading-none": "line height 1",
  "leading-tight": "tight line height",
  "leading-snug": "snug line height",
  "leading-normal": "normal line height",
  "leading-relaxed": "relaxed line height",
  "leading-loose": "loose line height",
  "leading-3": "line height 0.75rem",
  "leading-4": "line height 1rem",
  "leading-5": "line height 1.25rem",
  "leading-6": "line height 1.5rem",
  "leading-7": "line height 1.75rem",
  "leading-8": "line height 2rem",
  "leading-9": "line height 2.25rem",
  "leading-10": "line height 2.5rem",

  // Tracking (Letter Spacing)
  "tracking-tighter": "tighter letter spacing",
  "tracking-tight": "tight letter spacing",
  "tracking-normal": "normal letter spacing",
  "tracking-wide": "wide letter spacing",
  "tracking-wider": "wider letter spacing",
  "tracking-widest": "widest letter spacing",

  // List Style Type
  "list-none": "no list markers",
  "list-disc": "disc list markers",
  "list-decimal": "decimal list markers",

  // List Style Position
  "list-inside": "list markers inside",
  "list-outside": "list markers outside",

  // Text Transform
  uppercase: "UPPERCASE text",
  lowercase: "lowercase text",
  capitalize: "Capitalized Text",
  "normal-case": "normal case text",

  // Text Indent
  "indent-0": "no text indent",
  "indent-px": "1px text indent",
  "indent-0.5": "0.125rem text indent",
  "indent-1": "0.25rem text indent",
  "indent-2": "0.5rem text indent",
  "indent-4": "1rem text indent",
  "indent-8": "2rem text indent",

  // Vertical Align
  "align-baseline": "aligns to baseline",
  "align-top": "aligns to top",
  "align-middle": "aligns to middle",
  "align-bottom": "aligns to bottom",
  "align-text-top": "aligns to text top",
  "align-text-bottom": "aligns to text bottom",
  "align-sub": "subscript alignment",
  "align-super": "superscript alignment",

  // Whitespace
  "whitespace-normal": "normal whitespace",
  "whitespace-nowrap": "no line wrapping",
  "whitespace-pre": "preserves whitespace",
  "whitespace-pre-line": "preserves line breaks",
  "whitespace-pre-wrap": "preserves whitespace and wraps",
  "whitespace-break-spaces": "breaks at spaces",

  // Word Break
  "break-normal": "normal word breaks",
  "break-words": "breaks words if needed",
  "break-all": "breaks all characters",
  "break-keep": "keeps words together",

  // Hyphens
  "hyphens-none": "no hyphenation",
  "hyphens-manual": "manual hyphenation",
  "hyphens-auto": "automatic hyphenation",

  // Text Decoration
  underline: "underlined text",
  "no-underline": "no underline",
  "line-through": "strikethrough",
  "decoration-solid": "solid decoration",
  "decoration-double": "double decoration",
  "decoration-dotted": "dotted decoration",
  "decoration-dashed": "dashed decoration",
  "decoration-wavy": "wavy decoration",
  "decoration-0": "no decoration thickness",
  "decoration-1": "thin decoration",
  "decoration-2": "medium decoration",
  "decoration-4": "thick decoration",
  "decoration-8": "very thick decoration",
  "underline-offset-0": "no underline offset",
  "underline-offset-1": "small underline offset",
  "underline-offset-2": "medium underline offset",
  "underline-offset-4": "large underline offset",
  "underline-offset-8": "extra large underline offset",

  // Border
  border: "has border",
  "border-2": "has 2px border",
  "border-4": "has 4px border",
  "border-t": "top border",
  "border-r": "right border",
  "border-b": "bottom border",
  "border-l": "left border",
  "border-gray-200": "light gray border",
  "border-gray-300": "gray border",

  // Divide (borders between children)
  "divide-x": "vertical dividers between children",
  "divide-x-0": "no vertical dividers",
  "divide-x-2": "2px vertical dividers",
  "divide-x-4": "4px vertical dividers",
  "divide-x-8": "8px vertical dividers",
  "divide-y": "horizontal dividers between children",
  "divide-y-0": "no horizontal dividers",
  "divide-y-2": "2px horizontal dividers",
  "divide-y-4": "4px horizontal dividers",
  "divide-y-8": "8px horizontal dividers",
  "divide-x-reverse": "reversed vertical dividers",
  "divide-y-reverse": "reversed horizontal dividers",

  // Outline
  outline: "has outline",
  "outline-0": "no outline",
  "outline-1": "1px outline",
  "outline-2": "2px outline",
  "outline-4": "4px outline",
  "outline-8": "8px outline",
  "outline-dashed": "dashed outline",
  "outline-dotted": "dotted outline",
  "outline-double": "double outline",
  "outline-offset-0": "no outline offset",
  "outline-offset-1": "1px outline offset",
  "outline-offset-2": "2px outline offset",
  "outline-offset-4": "4px outline offset",
  "outline-offset-8": "8px outline offset",
  "-outline-offset-1": "-1px outline offset",
  "-outline-offset-2": "-2px outline offset",
  "-outline-offset-4": "-4px outline offset",
  "-outline-offset-8": "-8px outline offset",
  "outline-white": "white outline",
  "outline-black": "black outline",
  "outline-transparent": "transparent outline",

  // Border Radius
  rounded: "rounded corners",
  "rounded-sm": "small rounded corners",
  "rounded-md": "medium rounded corners",
  "rounded-lg": "large rounded corners",
  "rounded-xl": "extra large rounded corners",
  "rounded-2xl": "2x large rounded corners",
  "rounded-3xl": "3x large rounded corners",
  "rounded-full": "fully circular",
  "rounded-none": "no rounded corners",

  // Ring Width
  ring: "has focus ring (3px)",
  "ring-0": "no ring",
  "ring-1": "1px ring",
  "ring-2": "2px ring",
  "ring-4": "4px ring",
  "ring-8": "8px ring",
  "ring-inset": "inset ring",

  // Ring Offset Width
  "ring-offset-0": "no ring offset",
  "ring-offset-1": "1px ring offset",
  "ring-offset-2": "2px ring offset",
  "ring-offset-4": "4px ring offset",
  "ring-offset-8": "8px ring offset",

  // Shadow
  "shadow-sm": "small shadow",
  shadow: "has shadow",
  "shadow-md": "medium shadow",
  "shadow-lg": "large shadow",
  "shadow-xl": "extra large shadow",
  "shadow-2xl": "2x large shadow",
  "shadow-none": "no shadow",

  // Isolation
  isolate: "creates new stacking context",
  "isolation-auto": "automatic stacking context",

  // Backdrop Filters
  "backdrop-blur-none": "no background blur",
  "backdrop-blur-sm": "small background blur",
  "backdrop-blur": "blurred background",
  "backdrop-blur-md": "medium background blur",
  "backdrop-blur-lg": "large background blur",
  "backdrop-blur-xl": "extra large background blur",
  "backdrop-blur-2xl": "2x large background blur",
  "backdrop-blur-3xl": "3x large background blur",
  "backdrop-brightness-0": "no backdrop brightness",
  "backdrop-brightness-50": "50% backdrop brightness",
  "backdrop-brightness-75": "75% backdrop brightness",
  "backdrop-brightness-90": "90% backdrop brightness",
  "backdrop-brightness-95": "95% backdrop brightness",
  "backdrop-brightness-100": "normal backdrop brightness",
  "backdrop-brightness-105": "105% backdrop brightness",
  "backdrop-brightness-110": "110% backdrop brightness",
  "backdrop-brightness-125": "125% backdrop brightness",
  "backdrop-brightness-150": "150% backdrop brightness",
  "backdrop-brightness-200": "200% backdrop brightness",
  "backdrop-contrast-0": "no backdrop contrast",
  "backdrop-contrast-50": "50% backdrop contrast",
  "backdrop-contrast-75": "75% backdrop contrast",
  "backdrop-contrast-100": "normal backdrop contrast",
  "backdrop-contrast-125": "125% backdrop contrast",
  "backdrop-contrast-150": "150% backdrop contrast",
  "backdrop-contrast-200": "200% backdrop contrast",
  "backdrop-grayscale-0": "no backdrop grayscale",
  "backdrop-grayscale": "backdrop grayscale",
  "backdrop-invert-0": "no backdrop invert",
  "backdrop-invert": "backdrop invert",
  "backdrop-opacity-0": "transparent backdrop",
  "backdrop-opacity-5": "5% backdrop opacity",
  "backdrop-opacity-10": "10% backdrop opacity",
  "backdrop-opacity-20": "20% backdrop opacity",
  "backdrop-opacity-25": "25% backdrop opacity",
  "backdrop-opacity-30": "30% backdrop opacity",
  "backdrop-opacity-40": "40% backdrop opacity",
  "backdrop-opacity-50": "50% backdrop opacity",
  "backdrop-opacity-60": "60% backdrop opacity",
  "backdrop-opacity-70": "70% backdrop opacity",
  "backdrop-opacity-75": "75% backdrop opacity",
  "backdrop-opacity-80": "80% backdrop opacity",
  "backdrop-opacity-90": "90% backdrop opacity",
  "backdrop-opacity-95": "95% backdrop opacity",
  "backdrop-opacity-100": "full backdrop opacity",
  "backdrop-saturate-0": "no backdrop saturation",
  "backdrop-saturate-50": "50% backdrop saturation",
  "backdrop-saturate-100": "normal backdrop saturation",
  "backdrop-saturate-150": "150% backdrop saturation",
  "backdrop-saturate-200": "200% backdrop saturation",
  "backdrop-sepia-0": "no backdrop sepia",
  "backdrop-sepia": "backdrop sepia",
  "backdrop-hue-rotate-0": "no backdrop hue rotation",
  "backdrop-hue-rotate-15": "15° backdrop hue rotation",
  "backdrop-hue-rotate-30": "30° backdrop hue rotation",
  "backdrop-hue-rotate-60": "60° backdrop hue rotation",
  "backdrop-hue-rotate-90": "90° backdrop hue rotation",
  "backdrop-hue-rotate-180": "180° backdrop hue rotation",

  // Position
  static: "normal positioning (static position)",
  fixed: "stays in place when scrolling (fixed position)",
  absolute: "positioned relative to parent (absolute position)",
  relative: "positioned relative to normal position (relative position)",
  sticky: "sticks to top when scrolling (sticky position)",

  // Position Values
  "top-0": "positioned at top edge",
  "right-0": "positioned at right edge",
  "bottom-0": "positioned at bottom edge",
  "left-0": "positioned at left edge",
  "inset-0": "positioned at all edges",

  // Z-Index
  "z-0": "z-index 0 (bottom layer)",
  "z-10": "z-index 10 (above default)",
  "z-20": "z-index 20 (higher)",
  "z-30": "z-index 30 (high)",
  "z-40": "z-index 40 (very high)",
  "z-50": "z-index 50 (top layer)",

  // Overflow
  "overflow-hidden": "hides overflow content",
  "overflow-auto": "scrolls when needed",
  "overflow-scroll": "always scrollable",
  "overflow-x-auto": "scrolls horizontally when needed",
  "overflow-y-auto": "scrolls vertically when needed",

  // Transitions
  transition: "animates all changes",
  "transition-none": "no transitions",
  "transition-all": "animates all properties",
  "transition-colors": "animates color changes",
  "transition-opacity": "animates fade in/out",
  "transition-transform": "animates movement/scaling",
  "transition-shadow": "animates shadow changes",
  "duration-75": "75ms duration",
  "duration-100": "100ms duration",
  "duration-150": "150ms duration",
  "duration-200": "200ms duration",
  "duration-300": "300ms duration",
  "duration-500": "500ms duration",
  "duration-700": "700ms duration",
  "duration-1000": "1000ms duration",
  "ease-linear": "linear timing",
  "ease-in": "ease-in timing",
  "ease-out": "ease-out timing",
  "ease-in-out": "ease-in-out timing",
  "delay-75": "75ms delay",
  "delay-100": "100ms delay",
  "delay-150": "150ms delay",
  "delay-200": "200ms delay",
  "delay-300": "300ms delay",
  "delay-500": "500ms delay",
  "delay-700": "700ms delay",
  "delay-1000": "1000ms delay",

  // Transform Scale
  "scale-0": "scale to 0%",
  "scale-50": "scale to 50%",
  "scale-75": "scale to 75%",
  "scale-90": "scale to 90%",
  "scale-95": "scale to 95%",
  "scale-100": "scale to 100%",
  "scale-105": "scale to 105%",
  "scale-110": "scale to 110%",
  "scale-125": "scale to 125%",
  "scale-150": "scale to 150%",
  "scale-x-0": "scale horizontally to 0%",
  "scale-x-50": "scale horizontally to 50%",
  "scale-x-75": "scale horizontally to 75%",
  "scale-x-100": "scale horizontally to 100%",
  "scale-x-125": "scale horizontally to 125%",
  "scale-x-150": "scale horizontally to 150%",
  "scale-y-0": "scale vertically to 0%",
  "scale-y-50": "scale vertically to 50%",
  "scale-y-75": "scale vertically to 75%",
  "scale-y-100": "scale vertically to 100%",
  "scale-y-125": "scale vertically to 125%",
  "scale-y-150": "scale vertically to 150%",

  // Transform Rotate
  "rotate-0": "rotate 0°",
  "rotate-1": "rotate 1°",
  "rotate-2": "rotate 2°",
  "rotate-3": "rotate 3°",
  "rotate-6": "rotate 6°",
  "rotate-12": "rotate 12°",
  "rotate-45": "rotate 45°",
  "rotate-90": "rotate 90°",
  "rotate-180": "rotate 180°",
  "-rotate-1": "rotate -1°",
  "-rotate-2": "rotate -2°",
  "-rotate-3": "rotate -3°",
  "-rotate-6": "rotate -6°",
  "-rotate-12": "rotate -12°",
  "-rotate-45": "rotate -45°",
  "-rotate-90": "rotate -90°",
  "-rotate-180": "rotate -180°",

  // Transform Translate
  "translate-x-0": "translate horizontally 0",
  "translate-x-px": "translate horizontally 1px",
  "translate-x-0.5": "translate horizontally 0.125rem",
  "translate-x-1": "translate horizontally 0.25rem",
  "translate-x-2": "translate horizontally 0.5rem",
  "translate-x-4": "translate horizontally 1rem",
  "translate-x-8": "translate horizontally 2rem",
  "translate-x-1/2": "translate horizontally 50%",
  "translate-x-full": "translate horizontally 100%",
  "-translate-x-1": "translate horizontally -0.25rem",
  "-translate-x-2": "translate horizontally -0.5rem",
  "-translate-x-4": "translate horizontally -1rem",
  "-translate-x-1/2": "translate horizontally -50%",
  "-translate-x-full": "translate horizontally -100%",
  "translate-y-0": "translate vertically 0",
  "translate-y-px": "translate vertically 1px",
  "translate-y-0.5": "translate vertically 0.125rem",
  "translate-y-1": "translate vertically 0.25rem",
  "translate-y-2": "translate vertically 0.5rem",
  "translate-y-4": "translate vertically 1rem",
  "translate-y-8": "translate vertically 2rem",
  "translate-y-1/2": "translate vertically 50%",
  "translate-y-full": "translate vertically 100%",
  "-translate-y-1": "translate vertically -0.25rem",
  "-translate-y-2": "translate vertically -0.5rem",
  "-translate-y-4": "translate vertically -1rem",
  "-translate-y-1/2": "translate vertically -50%",
  "-translate-y-full": "translate vertically -100%",

  // Transform Skew
  "skew-x-0": "skew horizontally 0°",
  "skew-x-1": "skew horizontally 1°",
  "skew-x-2": "skew horizontally 2°",
  "skew-x-3": "skew horizontally 3°",
  "skew-x-6": "skew horizontally 6°",
  "skew-x-12": "skew horizontally 12°",
  "-skew-x-1": "skew horizontally -1°",
  "-skew-x-2": "skew horizontally -2°",
  "-skew-x-3": "skew horizontally -3°",
  "-skew-x-6": "skew horizontally -6°",
  "-skew-x-12": "skew horizontally -12°",
  "skew-y-0": "skew vertically 0°",
  "skew-y-1": "skew vertically 1°",
  "skew-y-2": "skew vertically 2°",
  "skew-y-3": "skew vertically 3°",
  "skew-y-6": "skew vertically 6°",
  "skew-y-12": "skew vertically 12°",
  "-skew-y-1": "skew vertically -1°",
  "-skew-y-2": "skew vertically -2°",
  "-skew-y-3": "skew vertically -3°",
  "-skew-y-6": "skew vertically -6°",
  "-skew-y-12": "skew vertically -12°",

  // Transform Origin
  "origin-center": "transform from center",
  "origin-top": "transform from top",
  "origin-top-right": "transform from top right",
  "origin-right": "transform from right",
  "origin-bottom-right": "transform from bottom right",
  "origin-bottom": "transform from bottom",
  "origin-bottom-left": "transform from bottom left",
  "origin-left": "transform from left",
  "origin-top-left": "transform from top left",

  // Cursor
  "cursor-pointer": "clickable (hand cursor)",
  "cursor-not-allowed": "disabled (not allowed)",
  "cursor-default": "normal cursor",

  // Opacity
  "opacity-0": "invisible",
  "opacity-50": "50% opacity",
  "opacity-75": "75% opacity",
  "opacity-100": "fully opaque",

  // Container
  container: "centered container",
};
