// Tailwind class to plain English mappings
export const tailwindMappings: Record<string, string> = {
  // Display
  block: "display as block",
  "inline-block": "display as inline block",
  inline: "display inline",
  hidden: "not visible",

  // Flexbox Layout
  flex: "flexbox container",
  "flex-row": "horizontal layout",
  "flex-col": "stacks vertically",
  "flex-wrap": "wraps items to next line",
  "flex-nowrap": "prevents wrapping",
  "flex-1": "takes remaining space",
  "flex-auto": "flexible size",
  "flex-initial": "initial flex",
  "flex-none": "inflexible",
  "flex-grow": "can grow",
  "flex-grow-0": "cannot grow",
  "flex-shrink": "can shrink",
  "flex-shrink-0": "cannot shrink",
  grow: "can grow",
  "grow-0": "cannot grow",
  shrink: "can shrink",
  "shrink-0": "cannot shrink",

  // Grid
  grid: "grid container",
  "grid-cols-1": "one column",
  "grid-cols-2": "two columns",
  "grid-cols-3": "three columns",
  "grid-cols-4": "four columns",
  "grid-cols-12": "twelve columns",
  "col-span-1": "spans 1 column",
  "col-span-2": "spans 2 columns",
  "col-span-3": "spans 3 columns",
  "col-span-4": "spans 4 columns",
  "col-span-6": "spans 6 columns",
  "col-span-12": "spans 12 columns",
  "col-span-full": "spans all columns",
  "col-start-1": "starts at column 1",
  "col-start-2": "starts at column 2",
  "col-start-3": "starts at column 3",
  "col-end-1": "ends at column 1",
  "col-end-2": "ends at column 2",
  "col-end-3": "ends at column 3",
  "row-span-1": "spans 1 row",
  "row-span-2": "spans 2 rows",
  "row-span-3": "spans 3 rows",
  "row-span-full": "spans all rows",
  "row-start-1": "starts at row 1",
  "row-start-2": "starts at row 2",
  "row-start-3": "starts at row 3",
  "row-end-1": "ends at row 1",
  "row-end-2": "ends at row 2",
  "row-end-3": "ends at row 3",

  // Justify Content
  "justify-start": "aligns items to start",
  "justify-end": "aligns items to end",
  "justify-center": "centers items horizontally",
  "justify-between": "spreads items apart",
  "justify-around": "distributes space around items",

  // Align Items
  "items-start": "aligns items to top",
  "items-end": "aligns items to bottom",
  "items-center": "centers items vertically",
  "items-stretch": "stretches items to fill",

  // Gap
  "gap-0": "no gap",
  "gap-1": "gap 0.25rem",
  "gap-2": "gap 0.5rem",
  "gap-3": "gap 0.75rem",
  "gap-4": "gap 1rem",
  "gap-5": "gap 1.25rem",
  "gap-6": "gap 1.5rem",
  "gap-8": "gap 2rem",
  "gap-10": "gap 2.5rem",
  "gap-12": "gap 3rem",

  // Padding - All sides
  "p-0": "no padding",
  "p-1": "padding 0.25rem",
  "p-2": "padding 0.5rem",
  "p-3": "padding 0.75rem",
  "p-4": "padding 1rem",
  "p-5": "padding 1.25rem",
  "p-6": "padding 1.5rem",
  "p-8": "padding 2rem",
  "p-10": "padding 2.5rem",
  "p-12": "padding 3rem",

  // Padding - Horizontal/Vertical
  "px-2": "horizontal padding 0.5rem",
  "px-4": "horizontal padding 1rem",
  "px-6": "horizontal padding 1.5rem",
  "px-8": "horizontal padding 2rem",
  "py-2": "vertical padding 0.5rem",
  "py-4": "vertical padding 1rem",
  "py-6": "vertical padding 1.5rem",
  "py-8": "vertical padding 2rem",

  // Padding - Individual sides
  "pt-4": "top padding 1rem",
  "pr-4": "right padding 1rem",
  "pb-4": "bottom padding 1rem",
  "pl-4": "left padding 1rem",

  // Margin - All sides
  "m-0": "no margin",
  "m-auto": "centered with auto margin",
  "m-1": "margin 0.25rem",
  "m-2": "margin 0.5rem",
  "m-4": "margin 1rem",
  "m-6": "margin 1.5rem",
  "m-8": "margin 2rem",

  // Margin - Horizontal/Vertical
  "mx-auto": "horizontally centered",
  "mx-2": "horizontal margin 0.5rem",
  "mx-4": "horizontal margin 1rem",
  "my-2": "vertical margin 0.5rem",
  "my-4": "vertical margin 1rem",

  // Width
  "w-full": "full width",
  "w-screen": "full screen width",
  "w-auto": "auto width",
  "w-1/2": "half width",
  "w-1/3": "one third width",
  "w-2/3": "two thirds width",
  "w-1/4": "quarter width",
  "w-10": "width 2.5rem",
  "w-20": "width 5rem",
  "w-32": "width 8rem",
  "w-64": "width 16rem",

  // Max Width
  "max-w-xs": "max width extra small",
  "max-w-sm": "max width small",
  "max-w-md": "max width medium",
  "max-w-lg": "max width large",
  "max-w-xl": "max width extra large",
  "max-w-2xl": "max width 2xl",
  "max-w-3xl": "max width 3xl",
  "max-w-4xl": "max width 4xl",
  "max-w-5xl": "max width 5xl",
  "max-w-6xl": "max width 6xl",
  "max-w-7xl": "max width 7xl",
  "max-w-full": "max width full",
  "max-w-screen-sm": "max width small screen",
  "max-w-screen-md": "max width medium screen",
  "max-w-screen-lg": "max width large screen",
  "max-w-screen-xl": "max width extra large screen",

  // Height
  "h-full": "full height",
  "h-screen": "full screen height",
  "h-auto": "auto height",
  "h-10": "height 2.5rem",
  "h-20": "height 5rem",
  "h-32": "height 8rem",
  "h-64": "height 16rem",
  "min-h-screen": "minimum screen height",
  "min-h-full": "minimum full height",

  // Background Colors - Grays
  "bg-white": "white background",
  "bg-black": "black background",
  "bg-transparent": "transparent background",
  "bg-gray-50": "very light gray background",
  "bg-gray-100": "light gray background",
  "bg-gray-200": "lighter gray background",
  "bg-gray-300": "light gray background",
  "bg-gray-400": "medium light gray background",
  "bg-gray-500": "medium gray background",
  "bg-gray-600": "medium dark gray background",
  "bg-gray-700": "dark gray background",
  "bg-gray-800": "darker gray background",
  "bg-gray-900": "very dark gray background",

  // Background Colors - Blues
  "bg-blue-50": "very light blue background",
  "bg-blue-100": "light blue background",
  "bg-blue-500": "blue background",
  "bg-blue-600": "medium blue background",
  "bg-blue-700": "dark blue background",

  // Background Colors - Other
  "bg-red-500": "red background",
  "bg-green-500": "green background",
  "bg-yellow-500": "yellow background",
  "bg-purple-500": "purple background",
  "bg-pink-500": "pink background",

  // Text Colors - Grays
  "text-white": "white text",
  "text-black": "black text",
  "text-gray-50": "very light gray text",
  "text-gray-100": "light gray text",
  "text-gray-400": "medium light gray text",
  "text-gray-500": "medium gray text",
  "text-gray-600": "medium dark gray text",
  "text-gray-700": "dark gray text",
  "text-gray-800": "darker gray text",
  "text-gray-900": "very dark gray text",

  // Text Colors - Other
  "text-blue-500": "blue text",
  "text-blue-600": "medium blue text",
  "text-red-500": "red text",
  "text-green-500": "green text",

  // Text Size
  "text-xs": "extra small text",
  "text-sm": "small text",
  "text-base": "base text size",
  "text-lg": "large text",
  "text-xl": "extra large text",
  "text-2xl": "2x large text",
  "text-3xl": "3x large text",
  "text-4xl": "4x large text",
  "text-5xl": "5x large text",

  // Text Alignment
  "text-left": "left aligned text",
  "text-center": "center aligned text",
  "text-right": "right aligned text",
  "text-justify": "justified text",

  // Font Weight
  "font-thin": "thin weight",
  "font-light": "light weight",
  "font-normal": "normal weight",
  "font-medium": "medium weight",
  "font-semibold": "semi-bold weight",
  "font-bold": "bold weight",
  "font-extrabold": "extra bold weight",

  // Text Decoration
  underline: "underlined text",
  "no-underline": "no underline",
  "line-through": "strikethrough",
  "decoration-solid": "solid decoration",
  "decoration-double": "double decoration",
  "decoration-dotted": "dotted decoration",
  "decoration-dashed": "dashed decoration",
  "decoration-wavy": "wavy decoration",
  "decoration-0": "no decoration thickness",
  "decoration-1": "thin decoration",
  "decoration-2": "medium decoration",
  "decoration-4": "thick decoration",
  "decoration-8": "very thick decoration",
  "underline-offset-0": "no underline offset",
  "underline-offset-1": "small underline offset",
  "underline-offset-2": "medium underline offset",
  "underline-offset-4": "large underline offset",
  "underline-offset-8": "extra large underline offset",

  // Border
  border: "has border",
  "border-2": "has 2px border",
  "border-4": "has 4px border",
  "border-t": "top border",
  "border-r": "right border",
  "border-b": "bottom border",
  "border-l": "left border",
  "border-gray-200": "light gray border",
  "border-gray-300": "gray border",

  // Outline
  outline: "has outline",
  "outline-0": "no outline",
  "outline-1": "1px outline",
  "outline-2": "2px outline",
  "outline-4": "4px outline",
  "outline-8": "8px outline",
  "outline-dashed": "dashed outline",
  "outline-dotted": "dotted outline",
  "outline-double": "double outline",
  "outline-offset-0": "no outline offset",
  "outline-offset-1": "1px outline offset",
  "outline-offset-2": "2px outline offset",
  "outline-offset-4": "4px outline offset",
  "outline-offset-8": "8px outline offset",
  "-outline-offset-1": "-1px outline offset",
  "-outline-offset-2": "-2px outline offset",
  "-outline-offset-4": "-4px outline offset",
  "-outline-offset-8": "-8px outline offset",
  "outline-white": "white outline",
  "outline-black": "black outline",
  "outline-transparent": "transparent outline",

  // Border Radius
  rounded: "rounded corners",
  "rounded-sm": "small rounded corners",
  "rounded-md": "medium rounded corners",
  "rounded-lg": "large rounded corners",
  "rounded-xl": "extra large rounded corners",
  "rounded-2xl": "2x large rounded corners",
  "rounded-3xl": "3x large rounded corners",
  "rounded-full": "fully circular",
  "rounded-none": "no rounded corners",

  // Shadow
  "shadow-sm": "small shadow",
  shadow: "has shadow",
  "shadow-md": "medium shadow",
  "shadow-lg": "large shadow",
  "shadow-xl": "extra large shadow",
  "shadow-2xl": "2x large shadow",
  "shadow-none": "no shadow",

  // Backdrop Filters
  "backdrop-blur-none": "no background blur",
  "backdrop-blur-sm": "small background blur",
  "backdrop-blur": "blurred background",
  "backdrop-blur-md": "medium background blur",
  "backdrop-blur-lg": "large background blur",
  "backdrop-blur-xl": "extra large background blur",
  "backdrop-blur-2xl": "2x large background blur",
  "backdrop-blur-3xl": "3x large background blur",
  "backdrop-brightness-0": "no backdrop brightness",
  "backdrop-brightness-50": "50% backdrop brightness",
  "backdrop-brightness-75": "75% backdrop brightness",
  "backdrop-brightness-90": "90% backdrop brightness",
  "backdrop-brightness-95": "95% backdrop brightness",
  "backdrop-brightness-100": "normal backdrop brightness",
  "backdrop-brightness-105": "105% backdrop brightness",
  "backdrop-brightness-110": "110% backdrop brightness",
  "backdrop-brightness-125": "125% backdrop brightness",
  "backdrop-brightness-150": "150% backdrop brightness",
  "backdrop-brightness-200": "200% backdrop brightness",
  "backdrop-contrast-0": "no backdrop contrast",
  "backdrop-contrast-50": "50% backdrop contrast",
  "backdrop-contrast-75": "75% backdrop contrast",
  "backdrop-contrast-100": "normal backdrop contrast",
  "backdrop-contrast-125": "125% backdrop contrast",
  "backdrop-contrast-150": "150% backdrop contrast",
  "backdrop-contrast-200": "200% backdrop contrast",
  "backdrop-grayscale-0": "no backdrop grayscale",
  "backdrop-grayscale": "backdrop grayscale",
  "backdrop-invert-0": "no backdrop invert",
  "backdrop-invert": "backdrop invert",
  "backdrop-opacity-0": "transparent backdrop",
  "backdrop-opacity-5": "5% backdrop opacity",
  "backdrop-opacity-10": "10% backdrop opacity",
  "backdrop-opacity-20": "20% backdrop opacity",
  "backdrop-opacity-25": "25% backdrop opacity",
  "backdrop-opacity-30": "30% backdrop opacity",
  "backdrop-opacity-40": "40% backdrop opacity",
  "backdrop-opacity-50": "50% backdrop opacity",
  "backdrop-opacity-60": "60% backdrop opacity",
  "backdrop-opacity-70": "70% backdrop opacity",
  "backdrop-opacity-75": "75% backdrop opacity",
  "backdrop-opacity-80": "80% backdrop opacity",
  "backdrop-opacity-90": "90% backdrop opacity",
  "backdrop-opacity-95": "95% backdrop opacity",
  "backdrop-opacity-100": "full backdrop opacity",
  "backdrop-saturate-0": "no backdrop saturation",
  "backdrop-saturate-50": "50% backdrop saturation",
  "backdrop-saturate-100": "normal backdrop saturation",
  "backdrop-saturate-150": "150% backdrop saturation",
  "backdrop-saturate-200": "200% backdrop saturation",
  "backdrop-sepia-0": "no backdrop sepia",
  "backdrop-sepia": "backdrop sepia",
  "backdrop-hue-rotate-0": "no backdrop hue rotation",
  "backdrop-hue-rotate-15": "15° backdrop hue rotation",
  "backdrop-hue-rotate-30": "30° backdrop hue rotation",
  "backdrop-hue-rotate-60": "60° backdrop hue rotation",
  "backdrop-hue-rotate-90": "90° backdrop hue rotation",
  "backdrop-hue-rotate-180": "180° backdrop hue rotation",

  // Position
  static: "static position",
  fixed: "fixed position",
  absolute: "absolute position",
  relative: "relative position",
  sticky: "sticky position",

  // Position Values
  "top-0": "top 0",
  "right-0": "right 0",
  "bottom-0": "bottom 0",
  "left-0": "left 0",
  "inset-0": "all sides 0",

  // Z-Index
  "z-0": "z-index 0 (bottom layer)",
  "z-10": "z-index 10 (above default)",
  "z-20": "z-index 20 (higher)",
  "z-30": "z-index 30 (high)",
  "z-40": "z-index 40 (very high)",
  "z-50": "z-index 50 (top layer)",

  // Overflow
  "overflow-hidden": "hides overflow content",
  "overflow-auto": "scrolls when needed",
  "overflow-scroll": "always scrollable",
  "overflow-x-auto": "scrolls horizontally when needed",
  "overflow-y-auto": "scrolls vertically when needed",

  // Transitions
  transition: "animates all changes",
  "transition-colors": "animates color changes",
  "transition-opacity": "animates fade in/out",
  "transition-transform": "animates movement/scaling",
  "transition-shadow": "animates shadow changes",
  "duration-150": "150ms duration",
  "duration-200": "200ms duration",
  "duration-300": "300ms duration",
  "ease-in": "ease-in timing",
  "ease-out": "ease-out timing",

  // Cursor
  "cursor-pointer": "clickable (hand cursor)",
  "cursor-not-allowed": "disabled (not allowed)",
  "cursor-default": "normal cursor",

  // Opacity
  "opacity-0": "invisible",
  "opacity-50": "50% opacity",
  "opacity-75": "75% opacity",
  "opacity-100": "fully opaque",

  // Container
  container: "centered container",
};
