// Tailwind class to plain English mappings
export const tailwindMappings: Record<string, string> = {
  // Display
  block: "display as block",
  "inline-block": "display as inline block",
  inline: "display inline",
  "inline-flex": "inline flex container",
  "inline-grid": "inline grid container",
  table: "display as table",
  "inline-table": "display as inline table",
  "table-caption": "display as table caption",
  "table-cell": "display as table cell",
  "table-column": "display as table column",
  "table-column-group": "display as table column group",
  "table-footer-group": "display as table footer group",
  "table-header-group": "display as table header group",
  "table-row-group": "display as table row group",
  "table-row": "display as table row",
  "flow-root": "flow-root display",
  contents: "contents only (no box)",
  "list-item": "display as list item",
  hidden: "not visible",

  // Visibility
  visible: "visible",
  invisible: "hidden but takes up space",
  collapse: "collapses table rows/columns",

  // Float
  "float-start": "floats to start side",
  "float-end": "floats to end side",
  "float-right": "floats to right",
  "float-left": "floats to left",
  "float-none": "no float",

  // Clear
  "clear-start": "clears start side floats",
  "clear-end": "clears end side floats",
  "clear-left": "clears left floats",
  "clear-right": "clears right floats",
  "clear-both": "clears both side floats",
  "clear-none": "no clear",

  // Box Sizing
  "box-border": "includes border and padding in size",
  "box-content": "excludes border and padding from size",

  // Columns
  "columns-1": "one column layout",
  "columns-2": "two column layout",
  "columns-3": "three column layout",
  "columns-4": "four column layout",
  "columns-5": "five column layout",
  "columns-6": "six column layout",
  "columns-7": "seven column layout",
  "columns-8": "eight column layout",
  "columns-9": "nine column layout",
  "columns-10": "ten column layout",
  "columns-11": "eleven column layout",
  "columns-12": "twelve column layout",
  "columns-auto": "automatic column count",
  "columns-3xs": "3xs column width",
  "columns-2xs": "2xs column width",
  "columns-xs": "xs column width",
  "columns-sm": "small column width",
  "columns-md": "medium column width",
  "columns-lg": "large column width",
  "columns-xl": "extra large column width",
  "columns-2xl": "2xl column width",
  "columns-3xl": "3xl column width",

  // Break Before
  "break-before-auto": "auto break before",
  "break-before-avoid": "avoid break before",
  "break-before-all": "break before always",
  "break-before-avoid-page": "avoid page break before",
  "break-before-page": "page break before",
  "break-before-left": "left page break before",
  "break-before-right": "right page break before",
  "break-before-column": "column break before",

  // Break After
  "break-after-auto": "auto break after",
  "break-after-avoid": "avoid break after",
  "break-after-all": "break after always",
  "break-after-avoid-page": "avoid page break after",
  "break-after-page": "page break after",
  "break-after-left": "left page break after",
  "break-after-right": "right page break after",
  "break-after-column": "column break after",

  // Break Inside
  "break-inside-auto": "auto break inside",
  "break-inside-avoid": "avoid break inside",
  "break-inside-avoid-page": "avoid page break inside",
  "break-inside-avoid-column": "avoid column break inside",

  // Object Fit
  "object-contain": "scales to fit while maintaining aspect ratio",
  "object-cover": "covers container while maintaining aspect ratio",
  "object-fill": "stretches to fill container",
  "object-none": "not resized",
  "object-scale-down": "scales down to fit (contain or none)",

  // Object Position
  "object-bottom": "positions content at bottom",
  "object-center": "positions content at center",
  "object-left": "positions content at left",
  "object-left-bottom": "positions content at left bottom",
  "object-left-top": "positions content at left top",
  "object-right": "positions content at right",
  "object-right-bottom": "positions content at right bottom",
  "object-right-top": "positions content at right top",
  "object-top": "positions content at top",

  // Flexbox Layout
  flex: "flexbox container",
  "flex-row": "horizontal layout",
  "flex-col": "stacks vertically",
  "flex-row-reverse": "reversed horizontal layout",
  "flex-col-reverse": "reversed vertical layout",
  "flex-wrap": "wraps items to next line",
  "flex-wrap-reverse": "wraps items in reverse",
  "flex-nowrap": "prevents wrapping",
  "flex-1": "takes remaining space",
  "flex-auto": "flexible size",
  "flex-initial": "initial flex",
  "flex-none": "inflexible",
  "flex-grow": "can grow",
  "flex-grow-0": "cannot grow",
  "flex-shrink": "can shrink",
  "flex-shrink-0": "cannot shrink",
  grow: "can grow",
  "grow-0": "cannot grow",
  shrink: "can shrink",
  "shrink-0": "cannot shrink",

  // Flex Basis
  "basis-0": "flex basis 0",
  "basis-px": "flex basis 1px",
  "basis-0.5": "flex basis 0.125rem",
  "basis-1": "flex basis 0.25rem",
  "basis-2": "flex basis 0.5rem",
  "basis-3": "flex basis 0.75rem",
  "basis-4": "flex basis 1rem",
  "basis-5": "flex basis 1.25rem",
  "basis-6": "flex basis 1.5rem",
  "basis-8": "flex basis 2rem",
  "basis-10": "flex basis 2.5rem",
  "basis-12": "flex basis 3rem",
  "basis-auto": "auto flex basis",
  "basis-full": "full flex basis",
  "basis-1/2": "half flex basis",
  "basis-1/3": "one third flex basis",
  "basis-2/3": "two thirds flex basis",
  "basis-1/4": "quarter flex basis",

  // Order
  "order-1": "order 1",
  "order-2": "order 2",
  "order-3": "order 3",
  "order-4": "order 4",
  "order-5": "order 5",
  "order-6": "order 6",
  "order-7": "order 7",
  "order-8": "order 8",
  "order-9": "order 9",
  "order-10": "order 10",
  "order-11": "order 11",
  "order-12": "order 12",
  "order-first": "order first (-9999)",
  "order-last": "order last (9999)",
  "order-none": "normal order (0)",

  // Grid
  grid: "grid container",
  "grid-flow-row": "grid flows by row",
  "grid-flow-col": "grid flows by column",
  "grid-flow-dense": "dense grid flow",
  "grid-flow-row-dense": "dense grid flow by row",
  "grid-flow-col-dense": "dense grid flow by column",
  "grid-flow-row-reverse": "grid flows by reversed rows",
  "grid-flow-col-reverse": "grid flows by reversed columns",
  "auto-cols-auto": "auto column width",
  "auto-cols-min": "minimum column width",
  "auto-cols-max": "maximum column width",
  "auto-cols-fr": "fractional column width",
  "auto-rows-auto": "auto row height",
  "auto-rows-min": "minimum row height",
  "auto-rows-max": "maximum row height",
  "auto-rows-fr": "fractional row height",
  "grid-cols-1": "one column",
  "grid-cols-2": "two columns",
  "grid-cols-3": "three columns",
  "grid-cols-4": "four columns",
  "grid-cols-5": "five columns",
  "grid-cols-6": "six columns",
  "grid-cols-7": "seven columns",
  "grid-cols-8": "eight columns",
  "grid-cols-9": "nine columns",
  "grid-cols-10": "ten columns",
  "grid-cols-11": "eleven columns",
  "grid-cols-12": "twelve columns",
  "grid-cols-none": "no column template",
  "grid-cols-subgrid": "subgrid columns",
  "grid-rows-1": "one row",
  "grid-rows-2": "two rows",
  "grid-rows-3": "three rows",
  "grid-rows-4": "four rows",
  "grid-rows-5": "five rows",
  "grid-rows-6": "six rows",
  "grid-rows-7": "seven rows",
  "grid-rows-8": "eight rows",
  "grid-rows-9": "nine rows",
  "grid-rows-10": "ten rows",
  "grid-rows-11": "eleven rows",
  "grid-rows-12": "twelve rows",
  "grid-rows-none": "no row template",
  "grid-rows-subgrid": "subgrid rows",
  "col-auto": "auto column width",
  "col-span-1": "spans 1 column",
  "col-span-2": "spans 2 columns",
  "col-span-3": "spans 3 columns",
  "col-span-4": "spans 4 columns",
  "col-span-5": "spans 5 columns",
  "col-span-6": "spans 6 columns",
  "col-span-7": "spans 7 columns",
  "col-span-8": "spans 8 columns",
  "col-span-9": "spans 9 columns",
  "col-span-10": "spans 10 columns",
  "col-span-11": "spans 11 columns",
  "col-span-12": "spans 12 columns",
  "col-span-full": "spans all columns",
  "col-start-1": "starts at column 1",
  "col-start-2": "starts at column 2",
  "col-start-3": "starts at column 3",
  "col-start-auto": "auto column start",
  "col-end-1": "ends at column 1",
  "col-end-2": "ends at column 2",
  "col-end-3": "ends at column 3",
  "col-end-auto": "auto column end",
  "row-auto": "auto row height",
  "row-span-1": "spans 1 row",
  "row-span-2": "spans 2 rows",
  "row-span-3": "spans 3 rows",
  "row-span-4": "spans 4 rows",
  "row-span-5": "spans 5 rows",
  "row-span-6": "spans 6 rows",
  "row-span-7": "spans 7 rows",
  "row-span-8": "spans 8 rows",
  "row-span-9": "spans 9 rows",
  "row-span-10": "spans 10 rows",
  "row-span-11": "spans 11 rows",
  "row-span-12": "spans 12 rows",
  "row-span-full": "spans all rows",
  "row-start-1": "starts at row 1",
  "row-start-2": "starts at row 2",
  "row-start-3": "starts at row 3",
  "row-start-auto": "auto row start",
  "row-end-1": "ends at row 1",
  "row-end-2": "ends at row 2",
  "row-end-3": "ends at row 3",
  "row-end-auto": "auto row end",

  // Justify Content
  "justify-start": "aligns items to start",
  "justify-end": "aligns items to end",
  "justify-center": "centers items horizontally",
  "justify-between": "spreads items apart",
  "justify-around": "distributes space around items",
  "justify-evenly": "distributes space evenly",
  "justify-normal": "normal justify behavior",
  "justify-stretch": "stretches items to fill",

  // Justify Items (grid)
  "justify-items-start": "aligns grid items to start",
  "justify-items-end": "aligns grid items to end",
  "justify-items-center": "centers grid items",
  "justify-items-stretch": "stretches grid items",

  // Justify Self
  "justify-self-auto": "auto justify alignment",
  "justify-self-start": "aligns self to start",
  "justify-self-end": "aligns self to end",
  "justify-self-center": "centers self",
  "justify-self-stretch": "stretches self",

  // Align Content
  "content-normal": "normal content alignment",
  "content-center": "centers content",
  "content-start": "aligns content to start",
  "content-end": "aligns content to end",
  "content-between": "spreads content apart",
  "content-around": "distributes space around content",
  "content-evenly": "distributes content evenly",
  "content-baseline": "aligns content to baseline",
  "content-stretch": "stretches content",

  // Align Items
  "items-start": "aligns items to top",
  "items-end": "aligns items to bottom",
  "items-center": "centers items vertically",
  "items-baseline": "aligns items to baseline",
  "items-stretch": "stretches items to fill",

  // Align Self
  "self-auto": "auto self alignment",
  "self-start": "aligns self to start",
  "self-end": "aligns self to end",
  "self-center": "centers self",
  "self-stretch": "stretches self",
  "self-baseline": "aligns self to baseline",

  // Place Content (grid)
  "place-content-center": "centers content in both axes",
  "place-content-start": "aligns content to start in both axes",
  "place-content-end": "aligns content to end in both axes",
  "place-content-between": "spreads content in both axes",
  "place-content-around": "distributes space around in both axes",
  "place-content-evenly": "distributes evenly in both axes",
  "place-content-baseline": "aligns to baseline in both axes",
  "place-content-stretch": "stretches in both axes",

  // Place Items (grid)
  "place-items-start": "aligns items to start in both axes",
  "place-items-end": "aligns items to end in both axes",
  "place-items-center": "centers items in both axes",
  "place-items-baseline": "aligns items to baseline in both axes",
  "place-items-stretch": "stretches items in both axes",

  // Place Self (grid)
  "place-self-auto": "auto placement in both axes",
  "place-self-start": "aligns self to start in both axes",
  "place-self-end": "aligns self to end in both axes",
  "place-self-center": "centers self in both axes",
  "place-self-stretch": "stretches self in both axes",

  // Gap
  "gap-0": "no gap",
  "gap-px": "gap 1px",
  "gap-0.5": "gap 0.125rem",
  "gap-1": "gap 0.25rem",
  "gap-1.5": "gap 0.375rem",
  "gap-2": "gap 0.5rem",
  "gap-2.5": "gap 0.625rem",
  "gap-3": "gap 0.75rem",
  "gap-3.5": "gap 0.875rem",
  "gap-4": "gap 1rem",
  "gap-5": "gap 1.25rem",
  "gap-6": "gap 1.5rem",
  "gap-7": "gap 1.75rem",
  "gap-8": "gap 2rem",
  "gap-9": "gap 2.25rem",
  "gap-10": "gap 2.5rem",
  "gap-11": "gap 2.75rem",
  "gap-12": "gap 3rem",
  "gap-14": "gap 3.5rem",
  "gap-16": "gap 4rem",
  "gap-x-0": "no horizontal gap",
  "gap-x-px": "horizontal gap 1px",
  "gap-x-0.5": "horizontal gap 0.125rem",
  "gap-x-1": "horizontal gap 0.25rem",
  "gap-x-2": "horizontal gap 0.5rem",
  "gap-x-3": "horizontal gap 0.75rem",
  "gap-x-4": "horizontal gap 1rem",
  "gap-x-6": "horizontal gap 1.5rem",
  "gap-x-8": "horizontal gap 2rem",
  "gap-y-0": "no vertical gap",
  "gap-y-px": "vertical gap 1px",
  "gap-y-0.5": "vertical gap 0.125rem",
  "gap-y-1": "vertical gap 0.25rem",
  "gap-y-2": "vertical gap 0.5rem",
  "gap-y-3": "vertical gap 0.75rem",
  "gap-y-4": "vertical gap 1rem",
  "gap-y-6": "vertical gap 1.5rem",
  "gap-y-8": "vertical gap 2rem",

  // Space Between
  "space-x-0": "no horizontal space between",
  "space-x-px": "1px horizontal space between",
  "space-x-0.5": "0.125rem horizontal space between",
  "space-x-1": "0.25rem horizontal space between",
  "space-x-2": "0.5rem horizontal space between",
  "space-x-3": "0.75rem horizontal space between",
  "space-x-4": "1rem horizontal space between",
  "space-x-6": "1.5rem horizontal space between",
  "space-x-8": "2rem horizontal space between",
  "space-x-reverse": "reversed horizontal space",
  "space-y-0": "no vertical space between",
  "space-y-px": "1px vertical space between",
  "space-y-0.5": "0.125rem vertical space between",
  "space-y-1": "0.25rem vertical space between",
  "space-y-2": "0.5rem vertical space between",
  "space-y-3": "0.75rem vertical space between",
  "space-y-4": "1rem vertical space between",
  "space-y-6": "1.5rem vertical space between",
  "space-y-8": "2rem vertical space between",
  "space-y-reverse": "reversed vertical space",

  // Padding - All sides
  "p-0": "no padding",
  "p-1": "padding 0.25rem",
  "p-2": "padding 0.5rem",
  "p-3": "padding 0.75rem",
  "p-4": "padding 1rem",
  "p-5": "padding 1.25rem",
  "p-6": "padding 1.5rem",
  "p-8": "padding 2rem",
  "p-10": "padding 2.5rem",
  "p-12": "padding 3rem",

  // Padding - Horizontal/Vertical
  "px-2": "horizontal padding 0.5rem",
  "px-4": "horizontal padding 1rem",
  "px-6": "horizontal padding 1.5rem",
  "px-8": "horizontal padding 2rem",
  "py-2": "vertical padding 0.5rem",
  "py-4": "vertical padding 1rem",
  "py-6": "vertical padding 1.5rem",
  "py-8": "vertical padding 2rem",

  // Padding - Individual sides
  "pt-4": "top padding 1rem",
  "pr-4": "right padding 1rem",
  "pb-4": "bottom padding 1rem",
  "pl-4": "left padding 1rem",

  // Margin - All sides
  "m-0": "no margin",
  "m-auto": "centered with auto margin",
  "m-1": "margin 0.25rem",
  "m-2": "margin 0.5rem",
  "m-4": "margin 1rem",
  "m-6": "margin 1.5rem",
  "m-8": "margin 2rem",

  // Margin - Horizontal/Vertical
  "mx-auto": "horizontally centered",
  "mx-2": "horizontal margin 0.5rem",
  "mx-4": "horizontal margin 1rem",
  "my-2": "vertical margin 0.5rem",
  "my-4": "vertical margin 1rem",

  // Width
  "w-full": "full width",
  "w-screen": "full screen width",
  "w-auto": "auto width",
  "w-1/2": "half width",
  "w-1/3": "one third width",
  "w-2/3": "two thirds width",
  "w-1/4": "quarter width",
  "w-10": "width 2.5rem",
  "w-20": "width 5rem",
  "w-32": "width 8rem",
  "w-64": "width 16rem",
  "min-w-0": "no minimum width",
  "min-w-full": "minimum full width",

  // Max Width
  "max-w-xs": "max width extra small",
  "max-w-sm": "max width small",
  "max-w-md": "max width medium",
  "max-w-lg": "max width large",
  "max-w-xl": "max width extra large",
  "max-w-2xl": "max width 2xl",
  "max-w-3xl": "max width 3xl",
  "max-w-4xl": "max width 4xl",
  "max-w-5xl": "max width 5xl",
  "max-w-6xl": "max width 6xl",
  "max-w-7xl": "max width 7xl",
  "max-w-full": "max width full",
  "max-w-screen-sm": "max width small screen",
  "max-w-screen-md": "max width medium screen",
  "max-w-screen-lg": "max width large screen",
  "max-w-screen-xl": "max width extra large screen",

  // Height
  "h-full": "full height",
  "h-screen": "full screen height",
  "h-auto": "auto height",
  "h-10": "height 2.5rem",
  "h-20": "height 5rem",
  "h-32": "height 8rem",
  "h-64": "height 16rem",
  "min-h-0": "no minimum height",
  "min-h-screen": "minimum screen height",
  "min-h-full": "minimum full height",
  "max-h-0": "max height 0",
  "max-h-full": "max full height",
  "max-h-screen": "max screen height",

  // Aspect Ratio
  "aspect-auto": "automatic aspect ratio",
  "aspect-square": "square aspect ratio (1:1)",
  "aspect-video": "video aspect ratio (16:9)",

  // Background Colors - Grays
  "bg-white": "white background",
  "bg-black": "black background",
  "bg-transparent": "transparent background",
  "bg-gray-50": "lightest gray background",
  "bg-gray-100": "very light gray background",
  "bg-gray-200": "light gray background",
  "bg-gray-300": "lightish gray background",
  "bg-gray-400": "medium light gray background",
  "bg-gray-500": "medium gray background",
  "bg-gray-600": "medium dark gray background",
  "bg-gray-700": "dark gray background",
  "bg-gray-800": "very dark gray background",
  "bg-gray-900": "darkest gray background",

  // Background Colors - Blues
  "bg-blue-50": "lightest blue background",
  "bg-blue-100": "very light blue background",
  "bg-blue-500": "blue background",
  "bg-blue-600": "medium dark blue background",
  "bg-blue-700": "dark blue background",

  // Background Colors - Other
  "bg-red-500": "red background",
  "bg-green-500": "green background",
  "bg-yellow-500": "yellow background",
  "bg-purple-500": "purple background",
  "bg-pink-500": "pink background",

  // Background Attachment
  "bg-fixed": "fixed background",
  "bg-local": "local background (scrolls with element)",
  "bg-scroll": "scrolling background",

  // Background Clip
  "bg-clip-border": "background includes border",
  "bg-clip-padding": "background includes padding",
  "bg-clip-content": "background within content only",
  "bg-clip-text": "background clips to text",

  // Background Origin
  "bg-origin-border": "background origin at border",
  "bg-origin-padding": "background origin at padding",
  "bg-origin-content": "background origin at content",

  // Background Position
  "bg-bottom": "background at bottom",
  "bg-center": "background at center",
  "bg-left": "background at left",
  "bg-left-bottom": "background at left bottom",
  "bg-left-top": "background at left top",
  "bg-right": "background at right",
  "bg-right-bottom": "background at right bottom",
  "bg-right-top": "background at right top",
  "bg-top": "background at top",

  // Background Repeat
  "bg-repeat": "repeating background",
  "bg-no-repeat": "non-repeating background",
  "bg-repeat-x": "background repeats horizontally",
  "bg-repeat-y": "background repeats vertically",
  "bg-repeat-round": "background repeats and scales to fit",
  "bg-repeat-space": "background repeats with spacing",

  // Background Size
  "bg-auto": "auto background size",
  "bg-cover": "background covers container",
  "bg-contain": "background contained within element",

  // Background Image
  "bg-none": "no background image",
  "bg-gradient-to-t": "gradient to top",
  "bg-gradient-to-tr": "gradient to top right",
  "bg-gradient-to-r": "gradient to right",
  "bg-gradient-to-br": "gradient to bottom right",
  "bg-gradient-to-b": "gradient to bottom",
  "bg-gradient-to-bl": "gradient to bottom left",
  "bg-gradient-to-l": "gradient to left",
  "bg-gradient-to-tl": "gradient to top left",

  // Text Colors - Grays
  "text-white": "white text",
  "text-black": "black text",
  "text-gray-50": "lightest gray text",
  "text-gray-100": "very light gray text",
  "text-gray-400": "medium light gray text",
  "text-gray-500": "medium gray text",
  "text-gray-600": "medium dark gray text",
  "text-gray-700": "dark gray text",
  "text-gray-800": "very dark gray text",
  "text-gray-900": "darkest gray text",

  // Text Colors - Other
  "text-blue-500": "blue text",
  "text-blue-600": "medium dark blue text",
  "text-red-500": "red text",
  "text-green-500": "green text",

  // Text Size
  "text-xs": "extra small text",
  "text-sm": "small text",
  "text-base": "base text size",
  "text-lg": "large text",
  "text-xl": "extra large text",
  "text-2xl": "2x large text",
  "text-3xl": "3x large text",
  "text-4xl": "4x large text",
  "text-5xl": "5x large text",
  "text-6xl": "6x large text",
  "text-7xl": "7x large text",
  "text-8xl": "8x large text",
  "text-9xl": "9x large text",

  // Text Alignment
  "text-left": "left aligned text",
  "text-center": "center aligned text",
  "text-right": "right aligned text",
  "text-justify": "justified text",

  // Text Overflow
  truncate: "cuts off text with ellipsis (...)",
  "text-ellipsis": "shows ellipsis for overflow",
  "text-clip": "clips overflow text",

  // Font Weight
  "font-thin": "thin weight",
  "font-extralight": "extra light weight",
  "font-light": "light weight",
  "font-normal": "normal weight",
  "font-medium": "medium weight",
  "font-semibold": "semi-bold weight",
  "font-bold": "bold weight",
  "font-extrabold": "extra bold weight",
  "font-black": "black weight",

  // Font Style
  italic: "italic text",
  "not-italic": "not italic",

  // Leading (Line Height)
  "leading-none": "line height 1",
  "leading-tight": "tight line height",
  "leading-snug": "snug line height",
  "leading-normal": "normal line height",
  "leading-relaxed": "relaxed line height",
  "leading-loose": "loose line height",
  "leading-3": "line height 0.75rem",
  "leading-4": "line height 1rem",
  "leading-5": "line height 1.25rem",
  "leading-6": "line height 1.5rem",
  "leading-7": "line height 1.75rem",
  "leading-8": "line height 2rem",
  "leading-9": "line height 2.25rem",
  "leading-10": "line height 2.5rem",

  // Tracking (Letter Spacing)
  "tracking-tighter": "tighter letter spacing",
  "tracking-tight": "tight letter spacing",
  "tracking-normal": "normal letter spacing",
  "tracking-wide": "wide letter spacing",
  "tracking-wider": "wider letter spacing",
  "tracking-widest": "widest letter spacing",

  // List Style Type
  "list-none": "no list markers",
  "list-disc": "disc list markers",
  "list-decimal": "decimal list markers",

  // List Style Position
  "list-inside": "list markers inside",
  "list-outside": "list markers outside",

  // Text Transform
  uppercase: "UPPERCASE text",
  lowercase: "lowercase text",
  capitalize: "Capitalized Text",
  "normal-case": "normal case text",

  // Text Indent
  "indent-0": "no text indent",
  "indent-px": "1px text indent",
  "indent-0.5": "0.125rem text indent",
  "indent-1": "0.25rem text indent",
  "indent-2": "0.5rem text indent",
  "indent-4": "1rem text indent",
  "indent-8": "2rem text indent",

  // Vertical Align
  "align-baseline": "aligns to baseline",
  "align-top": "aligns to top",
  "align-middle": "aligns to middle",
  "align-bottom": "aligns to bottom",
  "align-text-top": "aligns to text top",
  "align-text-bottom": "aligns to text bottom",
  "align-sub": "subscript alignment",
  "align-super": "superscript alignment",

  // Whitespace
  "whitespace-normal": "normal whitespace",
  "whitespace-nowrap": "no line wrapping",
  "whitespace-pre": "preserves whitespace",
  "whitespace-pre-line": "preserves line breaks",
  "whitespace-pre-wrap": "preserves whitespace and wraps",
  "whitespace-break-spaces": "breaks at spaces",

  // Word Break
  "break-normal": "normal word breaks",
  "break-words": "breaks words if needed",
  "break-all": "breaks all characters",
  "break-keep": "keeps words together",

  // Hyphens
  "hyphens-none": "no hyphenation",
  "hyphens-manual": "manual hyphenation",
  "hyphens-auto": "automatic hyphenation",

  // Text Decoration
  underline: "underlined text",
  "no-underline": "no underline",
  "line-through": "strikethrough",
  "decoration-solid": "solid decoration",
  "decoration-double": "double decoration",
  "decoration-dotted": "dotted decoration",
  "decoration-dashed": "dashed decoration",
  "decoration-wavy": "wavy decoration",
  "decoration-0": "no decoration thickness",
  "decoration-1": "thin decoration",
  "decoration-2": "medium decoration",
  "decoration-4": "thick decoration",
  "decoration-8": "very thick decoration",
  "underline-offset-0": "no underline offset",
  "underline-offset-1": "small underline offset",
  "underline-offset-2": "medium underline offset",
  "underline-offset-4": "large underline offset",
  "underline-offset-8": "extra large underline offset",
  "decoration-inherit": "decoration color inherits",
  "decoration-transparent": "transparent decoration color",
  "decoration-current": "decoration matches text color",

  // Border
  border: "has border",
  "border-0": "no border",
  "border-2": "has 2px border",
  "border-4": "has 4px border",
  "border-8": "has 8px border",
  "border-t": "top border",
  "border-t-0": "no top border",
  "border-t-2": "2px top border",
  "border-t-4": "4px top border",
  "border-r": "right border",
  "border-r-0": "no right border",
  "border-r-2": "2px right border",
  "border-r-4": "4px right border",
  "border-b": "bottom border",
  "border-b-0": "no bottom border",
  "border-b-2": "2px bottom border",
  "border-b-4": "4px bottom border",
  "border-l": "left border",
  "border-l-0": "no left border",
  "border-l-2": "2px left border",
  "border-l-4": "4px left border",
  "border-solid": "solid border",
  "border-dashed": "dashed border",
  "border-dotted": "dotted border",
  "border-double": "double border",
  "border-none": "no border",
  "border-transparent": "transparent border",
  "border-current": "border matches text color",
  "border-white": "white border",
  "border-black": "black border",
  "border-gray-200": "light gray border",
  "border-gray-300": "gray border",

  // Divide (borders between children)
  "divide-x": "vertical dividers between children",
  "divide-x-0": "no vertical dividers",
  "divide-x-2": "2px vertical dividers",
  "divide-x-4": "4px vertical dividers",
  "divide-x-8": "8px vertical dividers",
  "divide-y": "horizontal dividers between children",
  "divide-y-0": "no horizontal dividers",
  "divide-y-2": "2px horizontal dividers",
  "divide-y-4": "4px horizontal dividers",
  "divide-y-8": "8px horizontal dividers",
  "divide-x-reverse": "reversed vertical dividers",
  "divide-y-reverse": "reversed horizontal dividers",

  // Outline
  outline: "has outline",
  "outline-0": "no outline",
  "outline-1": "1px outline",
  "outline-2": "2px outline",
  "outline-4": "4px outline",
  "outline-8": "8px outline",
  "outline-none": "no outline",
  "outline-solid": "solid outline",
  "outline-dashed": "dashed outline",
  "outline-dotted": "dotted outline",
  "outline-double": "double outline",
  "outline-offset-0": "no outline offset",
  "outline-offset-1": "1px outline offset",
  "outline-offset-2": "2px outline offset",
  "outline-offset-4": "4px outline offset",
  "outline-offset-8": "8px outline offset",
  "-outline-offset-1": "-1px outline offset",
  "-outline-offset-2": "-2px outline offset",
  "-outline-offset-4": "-4px outline offset",
  "-outline-offset-8": "-8px outline offset",
  "outline-white": "white outline",
  "outline-black": "black outline",
  "outline-transparent": "transparent outline",

  // Border Radius
  rounded: "rounded corners",
  "rounded-none": "no rounded corners",
  "rounded-sm": "small rounded corners",

  "rounded-md": "medium rounded corners",
  "rounded-lg": "large rounded corners",
  "rounded-xl": "extra large rounded corners",
  "rounded-2xl": "2x large rounded corners",
  "rounded-3xl": "3x large rounded corners",
  "rounded-full": "fully circular",
  "rounded-t": "rounded top corners",
  "rounded-t-none": "no rounded top corners",
  "rounded-t-sm": "small rounded top corners",
  "rounded-t-md": "medium rounded top corners",
  "rounded-t-lg": "large rounded top corners",
  "rounded-r": "rounded right corners",
  "rounded-r-none": "no rounded right corners",
  "rounded-r-sm": "small rounded right corners",
  "rounded-r-md": "medium rounded right corners",
  "rounded-r-lg": "large rounded right corners",
  "rounded-b": "rounded bottom corners",
  "rounded-b-none": "no rounded bottom corners",
  "rounded-b-sm": "small rounded bottom corners",
  "rounded-b-md": "medium rounded bottom corners",
  "rounded-b-lg": "large rounded bottom corners",
  "rounded-l": "rounded left corners",
  "rounded-l-none": "no rounded left corners",
  "rounded-l-sm": "small rounded left corners",
  "rounded-l-md": "medium rounded left corners",
  "rounded-l-lg": "large rounded left corners",
  "rounded-tl": "rounded top-left corner",
  "rounded-tl-none": "no rounded top-left corner",
  "rounded-tl-sm": "small rounded top-left corner",
  "rounded-tl-md": "medium rounded top-left corner",
  "rounded-tl-lg": "large rounded top-left corner",
  "rounded-tr": "rounded top-right corner",
  "rounded-tr-none": "no rounded top-right corner",
  "rounded-tr-sm": "small rounded top-right corner",
  "rounded-tr-md": "medium rounded top-right corner",
  "rounded-tr-lg": "large rounded top-right corner",
  "rounded-bl": "rounded bottom-left corner",
  "rounded-bl-none": "no rounded bottom-left corner",
  "rounded-bl-sm": "small rounded bottom-left corner",
  "rounded-bl-md": "medium rounded bottom-left corner",
  "rounded-bl-lg": "large rounded bottom-left corner",
  "rounded-br": "rounded bottom-right corner",
  "rounded-br-none": "no rounded bottom-right corner",
  "rounded-br-sm": "small rounded bottom-right corner",
  "rounded-br-md": "medium rounded bottom-right corner",
  "rounded-br-lg": "large rounded bottom-right corner",

  // Ring Width
  ring: "has focus ring (3px)",
  "ring-0": "no ring",
  "ring-1": "1px ring",
  "ring-2": "2px ring",
  "ring-4": "4px ring",
  "ring-8": "8px ring",
  "ring-inset": "inset ring",

  // Ring Offset Width
  "ring-offset-0": "no ring offset",
  "ring-offset-1": "1px ring offset",
  "ring-offset-2": "2px ring offset",
  "ring-offset-4": "4px ring offset",
  "ring-offset-8": "8px ring offset",

  // Shadow
  "shadow-sm": "small shadow",
  shadow: "has shadow",
  "shadow-md": "medium shadow",
  "shadow-lg": "large shadow",
  "shadow-xl": "extra large shadow",
  "shadow-2xl": "2x large shadow",
  "shadow-none": "no shadow",

  // Isolation
  isolate: "creates new stacking context",
  "isolation-auto": "automatic stacking context",

  // Filters
  "blur-none": "no blur",
  "blur-sm": "small blur",
  blur: "medium blur",
  "blur-md": "medium blur",
  "blur-lg": "large blur",
  "blur-xl": "extra large blur",
  "blur-2xl": "2x large blur",
  "blur-3xl": "3x large blur",
  "brightness-0": "no brightness",
  "brightness-50": "50% brightness",
  "brightness-75": "75% brightness",
  "brightness-90": "90% brightness",
  "brightness-95": "95% brightness",
  "brightness-100": "normal brightness",
  "brightness-105": "105% brightness",
  "brightness-110": "110% brightness",
  "brightness-125": "125% brightness",
  "brightness-150": "150% brightness",
  "brightness-200": "200% brightness",
  "contrast-0": "no contrast",
  "contrast-50": "50% contrast",
  "contrast-75": "75% contrast",
  "contrast-100": "normal contrast",
  "contrast-125": "125% contrast",
  "contrast-150": "150% contrast",
  "contrast-200": "200% contrast",
  "drop-shadow-sm": "small drop shadow",
  "drop-shadow": "drop shadow",
  "drop-shadow-md": "medium drop shadow",
  "drop-shadow-lg": "large drop shadow",
  "drop-shadow-xl": "extra large drop shadow",
  "drop-shadow-2xl": "2x large drop shadow",
  "drop-shadow-none": "no drop shadow",
  "grayscale-0": "no grayscale",
  grayscale: "grayscale filter",
  "hue-rotate-0": "no hue rotation",
  "hue-rotate-15": "15° hue rotation",
  "hue-rotate-30": "30° hue rotation",
  "hue-rotate-60": "60° hue rotation",
  "hue-rotate-90": "90° hue rotation",
  "hue-rotate-180": "180° hue rotation",
  "-hue-rotate-15": "-15° hue rotation",
  "-hue-rotate-30": "-30° hue rotation",
  "-hue-rotate-60": "-60° hue rotation",
  "-hue-rotate-90": "-90° hue rotation",
  "-hue-rotate-180": "-180° hue rotation",
  "invert-0": "no invert",
  invert: "invert colors",
  "saturate-0": "no saturation",
  "saturate-50": "50% saturation",
  "saturate-100": "normal saturation",
  "saturate-150": "150% saturation",
  "saturate-200": "200% saturation",
  "sepia-0": "no sepia",
  sepia: "sepia filter",

  // Backdrop Filters
  "backdrop-blur-none": "no background blur",
  "backdrop-blur-sm": "small background blur",
  "backdrop-blur": "blurred background",
  "backdrop-blur-md": "medium background blur",
  "backdrop-blur-lg": "large background blur",
  "backdrop-blur-xl": "extra large background blur",
  "backdrop-blur-2xl": "2x large background blur",
  "backdrop-blur-3xl": "3x large background blur",
  "backdrop-brightness-0": "no backdrop brightness",
  "backdrop-brightness-50": "50% backdrop brightness",
  "backdrop-brightness-75": "75% backdrop brightness",
  "backdrop-brightness-90": "90% backdrop brightness",
  "backdrop-brightness-95": "95% backdrop brightness",
  "backdrop-brightness-100": "normal backdrop brightness",
  "backdrop-brightness-105": "105% backdrop brightness",
  "backdrop-brightness-110": "110% backdrop brightness",
  "backdrop-brightness-125": "125% backdrop brightness",
  "backdrop-brightness-150": "150% backdrop brightness",
  "backdrop-brightness-200": "200% backdrop brightness",
  "backdrop-contrast-0": "no backdrop contrast",
  "backdrop-contrast-50": "50% backdrop contrast",
  "backdrop-contrast-75": "75% backdrop contrast",
  "backdrop-contrast-100": "normal backdrop contrast",
  "backdrop-contrast-125": "125% backdrop contrast",
  "backdrop-contrast-150": "150% backdrop contrast",
  "backdrop-contrast-200": "200% backdrop contrast",
  "backdrop-grayscale-0": "no backdrop grayscale",
  "backdrop-grayscale": "backdrop grayscale",
  "backdrop-invert-0": "no backdrop invert",
  "backdrop-invert": "backdrop invert",
  "backdrop-opacity-0": "transparent backdrop",
  "backdrop-opacity-5": "5% backdrop opacity",
  "backdrop-opacity-10": "10% backdrop opacity",
  "backdrop-opacity-20": "20% backdrop opacity",
  "backdrop-opacity-25": "25% backdrop opacity",
  "backdrop-opacity-30": "30% backdrop opacity",
  "backdrop-opacity-40": "40% backdrop opacity",
  "backdrop-opacity-50": "50% backdrop opacity",
  "backdrop-opacity-60": "60% backdrop opacity",
  "backdrop-opacity-70": "70% backdrop opacity",
  "backdrop-opacity-75": "75% backdrop opacity",
  "backdrop-opacity-80": "80% backdrop opacity",
  "backdrop-opacity-90": "90% backdrop opacity",
  "backdrop-opacity-95": "95% backdrop opacity",
  "backdrop-opacity-100": "full backdrop opacity",
  "backdrop-saturate-0": "no backdrop saturation",
  "backdrop-saturate-50": "50% backdrop saturation",
  "backdrop-saturate-100": "normal backdrop saturation",
  "backdrop-saturate-150": "150% backdrop saturation",
  "backdrop-saturate-200": "200% backdrop saturation",
  "backdrop-sepia-0": "no backdrop sepia",
  "backdrop-sepia": "backdrop sepia",
  "backdrop-hue-rotate-0": "no backdrop hue rotation",
  "backdrop-hue-rotate-15": "15° backdrop hue rotation",
  "backdrop-hue-rotate-30": "30° backdrop hue rotation",
  "backdrop-hue-rotate-60": "60° backdrop hue rotation",
  "backdrop-hue-rotate-90": "90° backdrop hue rotation",
  "backdrop-hue-rotate-180": "180° backdrop hue rotation",

  // Position
  static: "normal positioning (static position)",
  fixed: "stays in place when scrolling (fixed position)",
  absolute: "positioned relative to parent (absolute position)",
  relative: "positioned relative to normal position (relative position)",
  sticky: "sticks to top when scrolling (sticky position)",

  // Position Values
  "top-0": "positioned at top edge",
  "right-0": "positioned at right edge",
  "bottom-0": "positioned at bottom edge",
  "left-0": "positioned at left edge",
  "inset-0": "positioned at all edges",
  "inset-x-0": "left & right at 0",
  "inset-x-px": "left & right at 1px",
  "inset-x-1": "left & right at 0.25rem",
  "inset-x-2": "left & right at 0.5rem",
  "inset-x-4": "left & right at 1rem",
  "inset-x-1/2": "horizontally centered (50%)",
  "inset-x-full": "left & right at 100%",
  "inset-y-0": "top & bottom at 0",
  "inset-y-px": "top & bottom at 1px",
  "inset-y-1": "top & bottom at 0.25rem",
  "inset-y-2": "top & bottom at 0.5rem",
  "inset-y-4": "top & bottom at 1rem",
  "inset-y-1/2": "vertically centered (50%)",
  "inset-y-full": "top & bottom at 100%",

  // Z-Index
  "z-0": "z-index 0 (bottom layer)",
  "z-10": "z-index 10 (above default)",
  "z-20": "z-index 20 (higher)",
  "z-30": "z-index 30 (high)",
  "z-40": "z-index 40 (very high)",
  "z-50": "z-index 50 (top layer)",

  // Overflow
  "overflow-auto": "scrolls when needed",
  "overflow-hidden": "hides overflow content",
  "overflow-clip": "clips overflow content",
  "overflow-visible": "shows overflow content",
  "overflow-scroll": "always scrollable",
  "overflow-x-auto": "scrolls horizontally when needed",
  "overflow-x-hidden": "hides horizontal overflow",
  "overflow-x-clip": "clips horizontal overflow",
  "overflow-x-visible": "shows horizontal overflow",
  "overflow-x-scroll": "always scrollable horizontally",
  "overflow-y-auto": "scrolls vertically when needed",
  "overflow-y-hidden": "hides vertical overflow",
  "overflow-y-clip": "clips vertical overflow",
  "overflow-y-visible": "shows vertical overflow",
  "overflow-y-scroll": "always scrollable vertically",

  // Overscroll Behavior
  "overscroll-auto": "auto overscroll behavior",
  "overscroll-contain": "contains overscroll",
  "overscroll-none": "no overscroll behavior",
  "overscroll-x-auto": "auto horizontal overscroll",
  "overscroll-x-contain": "contains horizontal overscroll",
  "overscroll-x-none": "no horizontal overscroll",
  "overscroll-y-auto": "auto vertical overscroll",
  "overscroll-y-contain": "contains vertical overscroll",
  "overscroll-y-none": "no vertical overscroll",

  // Transitions
  transition: "animates all changes",
  "transition-none": "no transitions",
  "transition-all": "animates all properties",
  "transition-colors": "animates color changes",
  "transition-opacity": "animates fade in/out",
  "transition-transform": "animates movement/scaling",
  "transition-shadow": "animates shadow changes",
  "duration-75": "75ms duration",
  "duration-100": "100ms duration",
  "duration-150": "150ms duration",
  "duration-200": "200ms duration",
  "duration-300": "300ms duration",
  "duration-500": "500ms duration",
  "duration-700": "700ms duration",
  "duration-1000": "1000ms duration",
  "ease-linear": "linear timing",
  "ease-in": "ease-in timing",
  "ease-out": "ease-out timing",
  "ease-in-out": "ease-in-out timing",
  "delay-75": "75ms delay",
  "delay-100": "100ms delay",
  "delay-150": "150ms delay",
  "delay-200": "200ms delay",
  "delay-300": "300ms delay",
  "delay-500": "500ms delay",
  "delay-700": "700ms delay",
  "delay-1000": "1000ms delay",

  // Transform Scale
  "scale-0": "scale to 0%",
  "scale-50": "scale to 50%",
  "scale-75": "scale to 75%",
  "scale-90": "scale to 90%",
  "scale-95": "scale to 95%",
  "scale-100": "scale to 100%",
  "scale-105": "scale to 105%",
  "scale-110": "scale to 110%",
  "scale-125": "scale to 125%",
  "scale-150": "scale to 150%",
  "scale-x-0": "scale horizontally to 0%",
  "scale-x-50": "scale horizontally to 50%",
  "scale-x-75": "scale horizontally to 75%",
  "scale-x-100": "scale horizontally to 100%",
  "scale-x-125": "scale horizontally to 125%",
  "scale-x-150": "scale horizontally to 150%",
  "scale-y-0": "scale vertically to 0%",
  "scale-y-50": "scale vertically to 50%",
  "scale-y-75": "scale vertically to 75%",
  "scale-y-100": "scale vertically to 100%",
  "scale-y-125": "scale vertically to 125%",
  "scale-y-150": "scale vertically to 150%",

  // Transform Rotate
  "rotate-0": "rotate 0°",
  "rotate-1": "rotate 1°",
  "rotate-2": "rotate 2°",
  "rotate-3": "rotate 3°",
  "rotate-6": "rotate 6°",
  "rotate-12": "rotate 12°",
  "rotate-45": "rotate 45°",
  "rotate-90": "rotate 90°",
  "rotate-180": "rotate 180°",
  "-rotate-1": "rotate -1°",
  "-rotate-2": "rotate -2°",
  "-rotate-3": "rotate -3°",
  "-rotate-6": "rotate -6°",
  "-rotate-12": "rotate -12°",
  "-rotate-45": "rotate -45°",
  "-rotate-90": "rotate -90°",
  "-rotate-180": "rotate -180°",

  // Transform Translate
  "translate-x-0": "translate horizontally 0",
  "translate-x-px": "translate horizontally 1px",
  "translate-x-0.5": "translate horizontally 0.125rem",
  "translate-x-1": "translate horizontally 0.25rem",
  "translate-x-2": "translate horizontally 0.5rem",
  "translate-x-4": "translate horizontally 1rem",
  "translate-x-8": "translate horizontally 2rem",
  "translate-x-1/2": "translate horizontally 50%",
  "translate-x-full": "translate horizontally 100%",
  "-translate-x-1": "translate horizontally -0.25rem",
  "-translate-x-2": "translate horizontally -0.5rem",
  "-translate-x-4": "translate horizontally -1rem",
  "-translate-x-1/2": "translate horizontally -50%",
  "-translate-x-full": "translate horizontally -100%",
  "translate-y-0": "translate vertically 0",
  "translate-y-px": "translate vertically 1px",
  "translate-y-0.5": "translate vertically 0.125rem",
  "translate-y-1": "translate vertically 0.25rem",
  "translate-y-2": "translate vertically 0.5rem",
  "translate-y-4": "translate vertically 1rem",
  "translate-y-8": "translate vertically 2rem",
  "translate-y-1/2": "translate vertically 50%",
  "translate-y-full": "translate vertically 100%",
  "-translate-y-1": "translate vertically -0.25rem",
  "-translate-y-2": "translate vertically -0.5rem",
  "-translate-y-4": "translate vertically -1rem",
  "-translate-y-1/2": "translate vertically -50%",
  "-translate-y-full": "translate vertically -100%",

  // Transform Skew
  "skew-x-0": "skew horizontally 0°",
  "skew-x-1": "skew horizontally 1°",
  "skew-x-2": "skew horizontally 2°",
  "skew-x-3": "skew horizontally 3°",
  "skew-x-6": "skew horizontally 6°",
  "skew-x-12": "skew horizontally 12°",
  "-skew-x-1": "skew horizontally -1°",
  "-skew-x-2": "skew horizontally -2°",
  "-skew-x-3": "skew horizontally -3°",
  "-skew-x-6": "skew horizontally -6°",
  "-skew-x-12": "skew horizontally -12°",
  "skew-y-0": "skew vertically 0°",
  "skew-y-1": "skew vertically 1°",
  "skew-y-2": "skew vertically 2°",
  "skew-y-3": "skew vertically 3°",
  "skew-y-6": "skew vertically 6°",
  "skew-y-12": "skew vertically 12°",
  "-skew-y-1": "skew vertically -1°",
  "-skew-y-2": "skew vertically -2°",
  "-skew-y-3": "skew vertically -3°",
  "-skew-y-6": "skew vertically -6°",
  "-skew-y-12": "skew vertically -12°",

  // Transform Origin
  "origin-center": "transform from center",
  "origin-top": "transform from top",
  "origin-top-right": "transform from top right",
  "origin-right": "transform from right",
  "origin-bottom-right": "transform from bottom right",
  "origin-bottom": "transform from bottom",
  "origin-bottom-left": "transform from bottom left",
  "origin-left": "transform from left",
  "origin-top-left": "transform from top left",

  // Backface Visibility
  "backface-visible": "backface is visible when rotated",
  "backface-hidden": "backface is hidden when rotated",

  // Cursor
  "cursor-auto": "auto cursor",
  "cursor-default": "normal cursor",
  "cursor-pointer": "clickable (hand cursor)",
  "cursor-wait": "waiting cursor",
  "cursor-text": "text cursor",
  "cursor-move": "move cursor",
  "cursor-help": "help cursor",
  "cursor-not-allowed": "disabled (not allowed)",
  "cursor-none": "no cursor",
  "cursor-context-menu": "context menu cursor",
  "cursor-progress": "progress cursor",
  "cursor-cell": "cell cursor",
  "cursor-crosshair": "crosshair cursor",
  "cursor-vertical-text": "vertical text cursor",
  "cursor-alias": "alias cursor",
  "cursor-copy": "copy cursor",
  "cursor-no-drop": "no drop cursor",
  "cursor-grab": "grab cursor",
  "cursor-grabbing": "grabbing cursor",
  "cursor-all-scroll": "all scroll cursor",
  "cursor-col-resize": "column resize cursor",
  "cursor-row-resize": "row resize cursor",
  "cursor-n-resize": "north resize cursor",
  "cursor-e-resize": "east resize cursor",
  "cursor-s-resize": "south resize cursor",
  "cursor-w-resize": "west resize cursor",
  "cursor-ne-resize": "northeast resize cursor",
  "cursor-nw-resize": "northwest resize cursor",
  "cursor-se-resize": "southeast resize cursor",
  "cursor-sw-resize": "southwest resize cursor",
  "cursor-ew-resize": "east-west resize cursor",
  "cursor-ns-resize": "north-south resize cursor",
  "cursor-nesw-resize": "northeast-southwest resize cursor",
  "cursor-nwse-resize": "northwest-southeast resize cursor",
  "cursor-zoom-in": "zoom in cursor",
  "cursor-zoom-out": "zoom out cursor",

  // Pointer Events
  "pointer-events-none": "ignores pointer events",
  "pointer-events-auto": "allows pointer events",

  // Resize
  "resize-none": "not resizable",
  "resize-x": "horizontally resizable",
  "resize-y": "vertically resizable",
  resize: "resizable in both directions",

  // Scroll Behavior
  "scroll-auto": "auto scroll behavior",
  "scroll-smooth": "smooth scrolling",

  // Scroll Snap Type
  "snap-none": "no scroll snap",
  "snap-x": "horizontal scroll snap",
  "snap-y": "vertical scroll snap",
  "snap-both": "scroll snap in both directions",
  "snap-mandatory": "mandatory scroll snap",
  "snap-proximity": "proximity scroll snap",

  // Scroll Snap Align
  "snap-start": "snap to start",
  "snap-end": "snap to end",
  "snap-center": "snap to center",
  "snap-align-none": "no snap alignment",

  // Scroll Snap Stop
  "snap-normal": "normal snap stop",
  "snap-always": "always snap stop",

  // Scroll Margin & Padding
  "scroll-m-0": "no scroll margin",
  "scroll-m-px": "1px scroll margin",
  "scroll-m-1": "0.25rem scroll margin",
  "scroll-m-2": "0.5rem scroll margin",
  "scroll-m-4": "1rem scroll margin",
  "scroll-p-0": "no scroll padding",
  "scroll-p-px": "1px scroll padding",
  "scroll-p-1": "0.25rem scroll padding",
  "scroll-p-2": "0.5rem scroll padding",
  "scroll-p-4": "1rem scroll padding",

  // Touch Action
  "touch-auto": "auto touch actions",
  "touch-none": "no touch actions",
  "touch-pan-x": "pan horizontally",
  "touch-pan-left": "pan left",
  "touch-pan-right": "pan right",
  "touch-pan-y": "pan vertically",
  "touch-pan-up": "pan up",
  "touch-pan-down": "pan down",
  "touch-pinch-zoom": "pinch to zoom",
  "touch-manipulation": "touch manipulation enabled",

  // User Select
  "select-none": "text not selectable",
  "select-text": "text selectable",
  "select-all": "selects all on click",
  "select-auto": "auto text selection",

  // Will Change
  "will-change-auto": "auto will-change",
  "will-change-scroll": "will change scroll position",
  "will-change-contents": "will change contents",
  "will-change-transform": "will change transform",

  // Appearance
  "appearance-none": "no default appearance",
  "appearance-auto": "default appearance",

  // Accent Color
  "accent-auto": "default accent color",
  "accent-transparent": "transparent accent color",
  "accent-current": "accent matches text color",
  "accent-inherit": "inherits accent color",

  // Caret Color
  "caret-transparent": "transparent caret color",
  "caret-current": "caret matches text color",
  "caret-inherit": "inherits caret color",

  // Animation
  "animate-none": "no animation",
  "animate-spin": "spinning animation",
  "animate-ping": "ping animation (scale and fade)",
  "animate-pulse": "pulsing animation (fade in/out)",
  "animate-bounce": "bouncing animation",

  // Mix Blend Mode
  "mix-blend-normal": "normal blend mode",
  "mix-blend-multiply": "multiply blend mode",
  "mix-blend-screen": "screen blend mode",
  "mix-blend-overlay": "overlay blend mode",
  "mix-blend-darken": "darken blend mode",
  "mix-blend-lighten": "lighten blend mode",
  "mix-blend-color-dodge": "color dodge blend mode",
  "mix-blend-color-burn": "color burn blend mode",
  "mix-blend-hard-light": "hard light blend mode",
  "mix-blend-soft-light": "soft light blend mode",
  "mix-blend-difference": "difference blend mode",
  "mix-blend-exclusion": "exclusion blend mode",
  "mix-blend-hue": "hue blend mode",
  "mix-blend-saturation": "saturation blend mode",
  "mix-blend-color": "color blend mode",
  "mix-blend-luminosity": "luminosity blend mode",
  "mix-blend-plus-darker": "plus darker blend mode",
  "mix-blend-plus-lighter": "plus lighter blend mode",

  // Background Blend Mode
  "bg-blend-normal": "normal background blend",
  "bg-blend-multiply": "multiply background blend",
  "bg-blend-screen": "screen background blend",
  "bg-blend-overlay": "overlay background blend",
  "bg-blend-darken": "darken background blend",
  "bg-blend-lighten": "lighten background blend",
  "bg-blend-color-dodge": "color dodge background blend",
  "bg-blend-color-burn": "color burn background blend",
  "bg-blend-hard-light": "hard light background blend",
  "bg-blend-soft-light": "soft light background blend",
  "bg-blend-difference": "difference background blend",
  "bg-blend-exclusion": "exclusion background blend",
  "bg-blend-hue": "hue background blend",
  "bg-blend-saturation": "saturation background blend",
  "bg-blend-color": "color background blend",
  "bg-blend-luminosity": "luminosity background blend",

  // Opacity
  "opacity-0": "invisible",
  "opacity-5": "5% opacity",
  "opacity-10": "10% opacity",
  "opacity-20": "20% opacity",
  "opacity-25": "25% opacity",
  "opacity-30": "30% opacity",
  "opacity-40": "40% opacity",
  "opacity-50": "50% opacity",
  "opacity-60": "60% opacity",
  "opacity-70": "70% opacity",
  "opacity-75": "75% opacity",
  "opacity-80": "80% opacity",
  "opacity-90": "90% opacity",
  "opacity-95": "95% opacity",
  "opacity-100": "fully opaque",

  // Container
  container: "centered container",

  // SVG Stroke Width
  "stroke-0": "no stroke",
  "stroke-1": "1px stroke",
  "stroke-2": "2px stroke",

  // SVG Fill
  "fill-none": "no fill",
  "fill-current": "fill with current color",

  // SVG Stroke
  "stroke-none": "no stroke",
  "stroke-current": "stroke with current color",

  // Table Layout
  "table-auto": "automatic table layout",
  "table-fixed": "fixed table layout",

  // Table Border Collapse
  "border-collapse": "collapsed table borders",
  "border-separate": "separated table borders",

  // Table Border Spacing
  "border-spacing-0": "no border spacing",
  "border-spacing-px": "1px border spacing",
  "border-spacing-0.5": "0.125rem border spacing",
  "border-spacing-1": "0.25rem border spacing",
  "border-spacing-2": "0.5rem border spacing",
  "border-spacing-4": "1rem border spacing",
  "border-spacing-8": "2rem border spacing",

  // Caption Side
  "caption-top": "caption at top",
  "caption-bottom": "caption at bottom",

  // Content (pseudo-elements)
  "content-none": "no content (for ::before/::after)",

  // Forced Color Adjust
  "forced-color-adjust-auto": "auto forced color adjust",
  "forced-color-adjust-none": "no forced color adjust",

  // Accessibility
  "sr-only": "screen reader only (visually hidden)",
  "not-sr-only": "visible to all (not just screen readers)",
};
